# Formatters for `nix fmt`, mirroring the formatting hooks in
# nix/devenv/modules/git-hooks.nix.
#
# flakelight dispatches per file: each key is a shell `case` pattern matched
# against the file's basename, and the command is invoked with the path as its
# final argument. Keys defined here override flakelight's builtinFormatters,
# which set them with mkDefault.
#
# The configs devenv installs into the repo root (biome.jsonc, rumdl.toml) are
# gitignored, so they are absent from the source `nix flake check` copies into
# the sandbox. Point at the store copies instead.
pkgs: let
  inherit (pkgs) alejandra biome coreutils gnused rustfmt tombi;
  inherit (pkgs.pkgsUnstable) nickel;

  # devenv has no YAML formatter, and the builtin prettier must not become one:
  # .tangled/workflows/*.yml is generated by `nickel export | yq` on every
  # devenv shell entry, and prettier rewrites yq's `'**'` to `"**"`. The two
  # would overwrite each other forever, leaving checks.formatting permanently
  # red. Override the builtin with a no-op rather than disabling
  # flakelight.builtinFormatters wholesale.
  noop = "${coreutils}/bin/true";

  # `cargo fmt` reads the edition from the crate's Cargo.toml; a bare `rustfmt`
  # would silently fall back to 2015 and mangle newer code. Walk up to the
  # nearest Cargo.toml that names an edition. A member using
  # `edition.workspace = true` has no literal edition, so the walk continues to
  # the workspace root's `[workspace.package]`.
  #
  # flakelight runs the formatter with an empty PATH whenever every command
  # carries store context, so every binary below is referenced absolutely.
  rustfmtEdition = pkgs.writeShellScript "rustfmt-edition" ''
    set -eu
    file="$1"
    dir="$(${coreutils}/bin/dirname "$file")"
    edition=2024
    while :; do
      if [ -f "$dir/Cargo.toml" ]; then
        found="$(${gnused}/bin/sed -n 's/^[[:space:]]*edition[[:space:]]*=[[:space:]]*"\([0-9]\{4\}\)".*/\1/p' "$dir/Cargo.toml" | ${coreutils}/bin/head -n1)"
        if [ -n "$found" ]; then
          edition="$found"
          break
        fi
      fi
      parent="$(${coreutils}/bin/dirname "$dir")"
      if [ "$parent" = "$dir" ]; then
        break
      fi
      dir="$parent"
    done
    exec ${rustfmt}/bin/rustfmt --edition "$edition" --quiet "$file"
  '';

  biomeFormat =
    "${biome}/bin/biome format --write"
    + " --config-path=${./devenv/modules/configs/biome-nix.jsonc}";
in {
  "*.nix" = "${alejandra}/bin/alejandra --quiet";
  # *.md is a no-op, not rumdl. rumdl has no cache.nixos.org build, so it
  # compiles from source, which overflows CI's tiny microVM disk and fails
  # checks.formatting. The no-op also stops the builtin prettier from taking
  # over *.md. Markdown is still formatted by the rumdl devenv git-hook on
  # commit.
  "*.md" = noop;
  "*.toml" = "${tombi}/bin/tombi format --offline";
  "*.ncl" = "${nickel}/bin/nickel format";
  "*.rs" = "${rustfmtEdition}";

  # Matches the devenv biome hook's types_or (javascript, jsx, ts, tsx,
  # json). CSS is deliberately absent: biome can format it, and the repo's
  # biome config lists it under files.includes, but the hook never passes it,
  # so `nix fmt` would restyle CSS that devenv leaves alone.
  "*.js" = biomeFormat;
  "*.jsx" = biomeFormat;
  "*.ts" = biomeFormat;
  "*.tsx" = biomeFormat;
  "*.json" = biomeFormat;

  "*.yaml" = noop;
  "*.yml" = noop;

  # *.mojo is deliberately absent. `mojo format` needs the ~900 MiB Modular
  # toolchain, which is not on cache.nixos.org, so pulling it into every
  # `nix fmt` and into checks.formatting is far too heavy — it alone makes
  # the formatting check unbuildable in CI's small microVM. Mojo files are
  # still formatted by the dedicated mojo-format devenv git-hook on commit.
}
