cmake_minimum_required(VERSION 3.13)
project(app C)
set(APP_VERSION "1.2.3")
configure_file(version.h.in version.h @ONLY)
add_library(greetlib STATIC src/greet.c)
target_include_directories(greetlib PUBLIC src/include)
add_executable(app src/main.c)
target_include_directories(app PRIVATE src/include "${CMAKE_CURRENT_BINARY_DIR}")
target_link_libraries(app greetlib)
