# Standalone build for the published repo. Generated by
# platform/tangled/publish/gen-project.nu; edit that template, not this file.
#
# The build, the devshell and its hooks, the formatter and the nixpkgs this
# resolves against are shared with every other repo published from the
# monorepo: the framework is nix-workspace, the Rust build is its modules/rust
# directory. Both are callable through one call, so what is particular to this
# project is all that is left to say.
{
  description = "A PipeWire-compatible multimedia graph daemon written in Rust";

  inputs = {
    workspace.url = "git+https://tangled.org/overby.me/nix-workspace";
    rust = {
      url = "git+https://tangled.org/overby.me/nix-workspace?dir=modules/rust";
      inputs.workspace.follows = "workspace";
    };

    # nix-lib carries buildCargoProject, which every project builds
    # with: one derivation per crate rather than one for the whole graph.
    nix-lib = {
      url = "git+https://tangled.org/overby.me/nix-lib";
      inputs.workspace.follows = "workspace";
    };
  };

  outputs = inputs:
    inputs.workspace {
      inherit inputs;
      rust.aliases = {
        "pipewire" = "oxidized-pipewire";
        "pipewire-pulse" = "oxidized-pipewire";
        "pipewire-aes67" = "oxidized-pipewire";
        "pipewire-avb" = "oxidized-pipewire";
        "pipewire-vulkan" = "oxidized-pipewire";
        "pw-cli" = "oxidized-pipewire";
        "pw-mon" = "oxidized-pipewire";
        "pw-dump" = "oxidized-pipewire";
        "pw-link" = "oxidized-pipewire";
        "pw-metadata" = "oxidized-pipewire";
        "pw-loopback" = "oxidized-pipewire";
        "pw-config" = "oxidized-pipewire";
        "pw-cat" = "oxidized-pipewire";
        "pw-play" = "oxidized-pipewire";
        "pw-record" = "oxidized-pipewire";
        "pw-dot" = "oxidized-pipewire";
        "pw-top" = "oxidized-pipewire";
        "pw-profiler" = "oxidized-pipewire";
        "pw-reserve" = "oxidized-pipewire";
        "pw-container" = "oxidized-pipewire";
        "pw-mididump" = "oxidized-pipewire";
        "pw-midiplay" = "oxidized-pipewire";
        "pw-midirecord" = "oxidized-pipewire";
        "pw-midi2play" = "oxidized-pipewire";
        "pw-midi2record" = "oxidized-pipewire";
        "pw-sysex" = "oxidized-pipewire";
        "pw-dsdplay" = "oxidized-pipewire";
        "pw-encplay" = "oxidized-pipewire";
        "pw-v4l2" = "oxidized-pipewire";
        "spa-json-dump" = "oxidized-pipewire";
        "spa-inspect" = "oxidized-pipewire";
        "spa-monitor" = "oxidized-pipewire";
        "spa-acp-tool" = "oxidized-pipewire";
        "spa-resample" = "oxidized-pipewire";
      };
    };
}
