# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
      kernelModules = [];
      luks.devices."luks-afab3f12-fda7-44c9-a2a0-4db26dc0d1b1".device = "/dev/disk/by-uuid/afab3f12-fda7-44c9-a2a0-4db26dc0d1b1";
    };
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/luks-afab3f12-fda7-44c9-a2a0-4db26dc0d1b1";
      fsType = "btrfs";
    };
    "/home" = {
      device = "/dev/mapper/luks-afab3f12-fda7-44c9-a2a0-4db26dc0d1b1";
      fsType = "btrfs";
      options = ["subvol=home"];
    };
    "/nix" = {
      device = "/dev/mapper/luks-afab3f12-fda7-44c9-a2a0-4db26dc0d1b1";
      fsType = "btrfs";
      options = ["subvol=nix"];
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/2A48-DDB0";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
