# Standalone build for the published repo. Generated by
# platform/tangled/publish/gen-project.nu; edit that template, not this file.
#
# The build, the devshell and its hooks, the formatter and the nixpkgs this
# resolves against are shared with every other repo published from the
# monorepo, and live in the nix-project flake. It is callable, so what is
# particular to this project is all that is left to say.
{
  description = "Gradual memory-safety hardening for unsafe Rust and mixed-language programs";

  inputs = {
    project.url = "github:overby-me/nix-project";

    # This project pins rustc through its own rust-toolchain.toml.
    rust-overlay.url = "github:oxalica/rust-overlay";
  };

  outputs = inputs:
    inputs.project ./. {
      name = "fe-c";
      description = "Gradual memory-safety hardening for unsafe Rust and mixed-language programs";
      toolchain = true;
      withOverlays = [inputs.rust-overlay.overlays.default];
    };
}
