# Standalone build for this project, as the monorepo sees it. Generated by
# platform/tangled/publish/gen-project.nu; edit that template, not this file.
#
# nix-workspace is a path here, so the monorepo can evaluate its own change to
# it without publishing first, and so the root flake can take this as an
# input and check that it still builds. The published repo gets the same file
# with a Tangled URL, mapped over this one by josh.
#
# The relative path only resolves when this flake is reached through the repo
# root: as a root input, or `nix eval '.?dir=<this directory>#...'`.
{
  description = "Gradual memory-safety hardening for unsafe Rust and mixed-language programs";

  inputs = {
    workspace.url = "path:../../platform/nix/workspace";

    # This project pins rustc through its own rust-toolchain.toml.
    rust-overlay.url = "github:oxalica/rust-overlay";
  };

  outputs = inputs:
    inputs.workspace ./. {
      name = "fe-c";
      description = "Gradual memory-safety hardening for unsafe Rust and mixed-language programs";
      toolchain = true;
      withOverlays = [inputs.rust-overlay.overlays.default];
    };
}
