# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod"];
      kernelModules = [];

      # LUKS2-encrypted root.  Unlock options:
      #   - Passphrase (always, primary fallback).
      #   - Nitrokey 3 FIDO2 hmac-secret (enrolled out-of-band with
      #     `systemd-cryptenroll --fido2-device=auto /dev/nvme0n1p3`).
      # systemd-initrd (boot.initrd.systemd.enable) is required for
      # FIDO2 unlock and is enabled in modules/nixos/core/boot.nix.
      luks.devices.cryptroot = {
        # Outer LUKS partition UUID (run `blkid /dev/nvme0n1p3` after
        # luksFormat, then update this).
        device = "/dev/disk/by-uuid/REPLACE-WITH-LUKS-PARTITION-UUID";
        allowDiscards = true;
        bypassWorkqueues = true;
        # FIDO2 keyslot is read from the LUKS header by systemd-cryptsetup;
        # no extra option needed here as long as the keyslot exists.
      };
    };
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };
  fileSystems."/" = {
    # Inner btrfs UUID (the filesystem inside /dev/mapper/cryptroot;
    # run `blkid /dev/mapper/cryptroot` after mkfs.btrfs and update).
    device = "/dev/disk/by-uuid/REPLACE-WITH-INNER-BTRFS-UUID";
    fsType = "btrfs";
    options = ["subvol=@" "noatime" "compress=zstd"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8AC7-C912";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
