# Standalone build for the published repo. Generated by
# platform/tangled/publish/gen-project.nu; edit that template, not this file.
#
# The build, the devshell and its hooks, the formatter and the nixpkgs this
# resolves against are shared with every other repo published from the
# monorepo: the framework is nix-workspace, the Rust build is its modules/rust
# directory. Both are callable through one call, so what is particular to this
# project is all that is left to say.
{
  description = "A GNU binutils-compatible suite of binary utilities written in Rust";

  inputs = {
    workspace.url = "git+https://tangled.org/overby.me/nix-workspace";
    rust = {
      url = "git+https://tangled.org/overby.me/nix-workspace?dir=modules/rust";
      inputs.workspace.follows = "workspace";
    };
  };

  outputs = inputs:
    inputs.workspace {
      inherit inputs;
      rust = {
        pname = "oxidized-binutils";
        aliases = {
          "ar" = "rust-binutils";
          "ranlib" = "rust-binutils";
          "nm" = "rust-binutils";
          "objdump" = "rust-binutils";
          "readelf" = "rust-binutils";
          "objcopy" = "rust-binutils";
          "strings" = "rust-binutils";
          "size" = "rust-binutils";
          "addr2line" = "rust-binutils";
          "c++filt" = "rust-binutils";
          "strip" = "rust-binutils";
          "as" = "rust-binutils";
          "ld" = "rust-binutils";
          "elfedit" = "rust-binutils";
        };
      };
    };
}
