// Bundle XR Web Examples — TypeScript → browser-ready JavaScript.
//
// The XR web runtime is written in TypeScript (.ts files). Browsers cannot
// execute TypeScript directly, so this script uses esbuild to bundle each
// XR example entry point into a self-contained ES module that browsers can
// load via <script type="module">.
//
// Usage:
//   deno run --allow-read --allow-write --allow-env --allow-run scripts/bundle.ts
//   deno run --allow-read --allow-write --allow-env --allow-run scripts/bundle.ts counter
//   deno run --allow-read --allow-write --allow-env --allow-run scripts/bundle.ts --clean
//
// Output:
//   xr/web/examples/{app}/bundle.js  — browser-ready ES module
//
// The HTML entry points load bundle.js via:
//   <script type="module" src="bundle.js"></script>
//
// The bundle includes the full XR runtime (xr-session, xr-panel, xr-renderer,
// xr-input, xr-runtime) and the shared web/runtime Interpreter + TemplateCache.
// It does NOT include the WASM binary — that's loaded at runtime via fetch().

import { dirname, fromFileUrl, resolve } from "jsr:@std/path";
import { build, stop } from "npm:esbuild@0.25.5";

// ── Configuration ───────────────────────────────────────────────────────────

const SCRIPT_DIR = dirname(fromFileUrl(import.meta.url));
const XR_WEB_DIR = resolve(SCRIPT_DIR, "..");

/** All example apps that have XR web entry points. */
const ALL_APPS = ["counter", "todo", "bench", "app"];

// ── Helpers ─────────────────────────────────────────────────────────────────

function log(msg: string): void {
	console.log(`[bundle] ${msg}`);
}

function logError(msg: string): void {
	console.error(`[bundle] ERROR: ${msg}`);
}

async function fileExists(path: string): Promise<boolean> {
	try {
		await Deno.stat(path);
		return true;
	} catch {
		return false;
	}
}

// ── Clean ───────────────────────────────────────────────────────────────────

async function clean(): Promise<void> {
	for (const app of ALL_APPS) {
		const bundlePath = resolve(XR_WEB_DIR, "examples", app, "bundle.js");
		const mapPath = `${bundlePath}.map`;
		for (const p of [bundlePath, mapPath]) {
			if (await fileExists(p)) {
				await Deno.remove(p);
				log(`removed ${p}`);
			}
		}
	}
	log("clean complete");
}

// ── Bundle ──────────────────────────────────────────────────────────────────

async function bundleApp(app: string): Promise<boolean> {
	const entryPoint = resolve(XR_WEB_DIR, "examples", app, "main.js");
	const outfile = resolve(XR_WEB_DIR, "examples", app, "bundle.js");

	if (!(await fileExists(entryPoint))) {
		logError(`entry point not found: ${entryPoint}`);
		return false;
	}

	log(`bundling ${app}…`);

	try {
		const result = await build({
			entryPoints: [entryPoint],
			bundle: true,
			outfile,
			format: "esm",
			platform: "browser",
			target: ["es2020"],
			sourcemap: true,
			minify: false, // Keep readable for debugging
			treeShaking: true,

			// Resolve .ts imports — esbuild handles TypeScript natively
			resolveExtensions: [".ts", ".js", ".mjs"],

			// The XR runtime imports from web/runtime/ via relative paths.
			// esbuild resolves these automatically from the file system.

			// Banner with attribution
			banner: {
				js: [
					"// XR Web Runtime — bundled for browser consumption.",
					`// App: ${app}`,
					`// Generated by: xr/web/scripts/bundle.ts`,
					`// Source: xr/web/examples/${app}/main.js`,
					"",
				].join("\n"),
			},
		});

		if (result.errors.length > 0) {
			for (const err of result.errors) {
				logError(`${err.text} (${err.location?.file}:${err.location?.line})`);
			}
			return false;
		}

		if (result.warnings.length > 0) {
			for (const warn of result.warnings) {
				log(`  warn: ${warn.text}`);
			}
		}

		log(`  → ${outfile}`);
		return true;
	} catch (err: unknown) {
		const msg = err instanceof Error ? err.message : String(err);
		logError(`failed to bundle ${app}: ${msg}`);
		return false;
	}
}

// ── Main ────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
	const args = Deno.args;

	// Handle --clean flag
	if (args.includes("--clean")) {
		await clean();
		stop();
		return;
	}

	// Determine which apps to bundle
	const apps: string[] = [];
	for (const arg of args) {
		if (arg.startsWith("-")) continue; // skip flags
		if (ALL_APPS.includes(arg)) {
			apps.push(arg);
		} else {
			logError(`unknown app: "${arg}" (available: ${ALL_APPS.join(", ")})`);
			stop();
			Deno.exit(1);
		}
	}

	// Default: bundle all apps
	const toBuild = apps.length > 0 ? apps : ALL_APPS;

	log(`bundling ${toBuild.length} app(s): ${toBuild.join(", ")}`);

	let failures = 0;
	for (const app of toBuild) {
		const ok = await bundleApp(app);
		if (!ok) failures++;
	}

	// esbuild keeps a child process alive — stop it explicitly
	stop();

	if (failures > 0) {
		logError(`${failures} bundle(s) failed`);
		Deno.exit(1);
	}

	log(`✅ ${toBuild.length} bundle(s) complete`);
}

await main();
