# Standalone build for the published repo. Generated by
# platform/tangled/publish/gen-project.nu; edit that template, not this file.
#
# The devshell and its hooks, the formatter and the nixpkgs this resolves
# against are shared with every other repo published from the monorepo, and
# arrive through nix-workspace. The build is the Rust module's: the
# monorepo builds this from its own default.nix, which this repo may not
# reach for, so the two differ here and nowhere else.
{
  description = "A Ninja-compatible build system written in Rust";

  inputs = {
    workspace.url = "git+https://tangled.org/overby.me/nix-workspace";

    # nix-lib builds with this project, so taking nix-lib here would be a
    # cycle. The Rust module builds it instead, as every repo did before
    # buildCargoProject.
    rust = {
      url = "git+https://tangled.org/overby.me/nix-workspace?dir=modules/rust";
      inputs.workspace.follows = "workspace";
    };
  };

  outputs = inputs:
    inputs.workspace {
      inherit inputs;
    };
}
