//! Port of `hacks/glx/dnalogo.c`.
//!
//! ```text
//! DNA Logo, Copyright (c) 2001-2018 Jamie Zawinski <jwz@jwz.org>
//!
//! Permission to use, copy, modify, distribute, and sell this software and its
//! documentation for any purpose is hereby granted without fee, provided that
//! the above copyright notice appear in all copies and that both that
//! copyright notice and this permission notice appear in supporting
//! documentation.  No representations are made about the suitability of this
//! software for any purpose.  It is provided "as is" without express or
//! implied warranty.
//! ```
//!
//! The DNA Lounge sign: a double helix inside a gasket, in a picture frame,
//! turning over on itself. Every so often the helix shrinks away and the DNA
//! Pizza slice grows in its place, and every so often the whole thing is
//! drawn again as a wireframe over itself for a few seconds.
//!
//! Nothing here is animated in the usual sense. Everything that turns is a
//! *spinner*: a thing that is usually still and occasionally decides, with
//! some fixed probability a frame, to make exactly one full revolution and
//! stop. Its position is eased at both ends so it starts and finishes slowly,
//! and the two scene spinners are linked, so that when one starts the other
//! is given a turn to start as well.
//!
//! The gasket is the interesting shape. It is not modelled: it is a list of
//! forty-odd radius and angle pairs read off the real sign, interpolated
//! between at eight degrees a step, and then extruded. The outer rim's
//! normals are averaged with their neighbours' except where two faces meet at
//! more than about thirty-five degrees, which is what keeps the corners sharp
//! and the curves smooth without anyone having to say which is which.
//!
//! The pizza slice is a shape with holes in it, which upstream fills with the
//! GLU tessellator. There is no tessellator here, and upstream's own OpenGL
//! ES build has none either, so it carries the slice as a list of triangles
//! that its desktop build's tessellator produced once and had saved. That is
//! the list used here.

#[cfg(not(target_arch = "wasm32"))]
use crate::runtime::Saver3d;
use crate::runtime::gl::Shape;
use crate::runtime::shapes::calc_normal;
use crate::runtime::tube::tube;
use crate::runtime::{
    About, Gl, Hack3d, Opt, Runner3d, SaverDef, SelectItem, StartArgs, Trackball, XEvent, frand,
    random, random_below,
};

mod pizza {
    /// The DNA Pizza slice, already cut into triangles.
    ///
    /// ```text
    /// DNA Pizza Logo, Copyright (c) 2011-2012 Jamie Zawinski <jwz@dnalounge.com>
    ///
    /// Since GLUtesselator doesn't exist in the iOS build, the slice shape
    /// of the DNA Pizza logo is hardcoded there, instead of being generated.
    /// (These vertexes were generated by GLUtesselator and saved.)
    /// ```
    #[rustfmt::skip]
    pub const TRIANGLES: &[f32] = &[
        0.315, 0.213301, 0.0, 0.296699, 0.195, 0.0, 0.309, 0.455, 0.0,
        0.296699, 0.195, 0.0, 0.29, 0.17, 0.0, 0.309, 0.455, 0.0,
        0.309, 0.455, 0.0, 0.29, 0.17, 0.0, 0.26, 0.452, 0.0,
        0.29, 0.17, 0.0, 0.23, 0.042, 0.0, 0.26, 0.452, 0.0,
        0.26, 0.452, 0.0, 0.23, 0.042, 0.0, 0.216, 0.293, 0.0,
        0.23, 0.042, 0.0, 0.21, 0.0, 0.0, 0.216, 0.293, 0.0,
        0.216, 0.293, 0.0, 0.21, 0.0, 0.0, 0.149, 0.178, 0.0,
        0.21, 0.0, 0.0, 0.102, 0.178, 0.0, 0.149, 0.178, 0.0,
        0.376, 0.572, 0.0, 0.353, 0.613, 0.0, 0.411, 0.68402, 0.0,
        0.376, 0.572, 0.0, 0.411, 0.68402, 0.0, 0.383301, 0.195, 0.0,
        0.376, 0.572, 0.0, 0.383301, 0.195, 0.0, 0.365, 0.213301, 0.0,
        0.376, 0.572, 0.0, 0.365, 0.213301, 0.0, 0.34, 0.22, 0.0,
        0.376, 0.572, 0.0, 0.34, 0.22, 0.0, 0.315, 0.213301, 0.0,
        0.376, 0.572, 0.0, 0.315, 0.213301, 0.0, 0.309, 0.455, 0.0,
        0.39, 0.17, 0.0, 0.383301, 0.195, 0.0, 0.411, 0.68402, 0.0,
        0.39, 0.17, 0.0, 0.411, 0.68402, 0.0, 0.48, 0.17, 0.0,
        0.39, 0.17, 0.0, 0.48, 0.17, 0.0, 0.488039, 0.14, 0.0,
        0.39, 0.17, 0.0, 0.488039, 0.14, 0.0, 0.51, 0.118038, 0.0,
        0.39, 0.17, 0.0, 0.51, 0.118038, 0.0, 0.616, 0.042, 0.0,
        0.39, 0.17, 0.0, 0.616, 0.042, 0.0, 0.383301, 0.145, 0.0,
        0.798, 0.0, 0.0, 0.641, 0.0, 0.0, 0.645595, 0.469053, 0.0,
        0.798, 0.0, 0.0, 0.645595, 0.469053, 0.0, 0.653683, 0.457714, 0.0,
        0.798, 0.0, 0.0, 0.653683, 0.457714, 0.0, 0.661572, 0.446236, 0.0,
        0.798, 0.0, 0.0, 0.661572, 0.446236, 0.0, 0.669259, 0.434622, 0.0,
        0.798, 0.0, 0.0, 0.669259, 0.434622, 0.0, 0.676742, 0.422876, 0.0,
        0.798, 0.0, 0.0, 0.676742, 0.422876, 0.0, 0.68402, 0.411, 0.0,
        0.798, 0.0, 0.0, 0.68402, 0.411, 0.0, 0.691088, 0.399, 0.0,
        0.798, 0.0, 0.0, 0.691088, 0.399, 0.0, 0.697947, 0.386878, 0.0,
        0.798, 0.0, 0.0, 0.697947, 0.386878, 0.0, 0.704592, 0.374638, 0.0,
        0.798, 0.0, 0.0, 0.704592, 0.374638, 0.0, 0.711023, 0.362284, 0.0,
        0.798, 0.0, 0.0, 0.711023, 0.362284, 0.0, 0.717238, 0.34982, 0.0,
        0.798, 0.0, 0.0, 0.717238, 0.34982, 0.0, 0.723234, 0.337249, 0.0,
        0.798, 0.0, 0.0, 0.723234, 0.337249, 0.0, 0.729009, 0.324576, 0.0,
        0.798, 0.0, 0.0, 0.729009, 0.324576, 0.0, 0.734563, 0.311803, 0.0,
        0.798, 0.0, 0.0, 0.734563, 0.311803, 0.0, 0.739893, 0.298936, 0.0,
        0.798, 0.0, 0.0, 0.739893, 0.298936, 0.0, 0.744997, 0.285978, 0.0,
        0.798, 0.0, 0.0, 0.744997, 0.285978, 0.0, 0.749875, 0.272932, 0.0,
        0.798, 0.0, 0.0, 0.749875, 0.272932, 0.0, 0.754524, 0.259803, 0.0,
        0.798, 0.0, 0.0, 0.754524, 0.259803, 0.0, 0.758943, 0.246596, 0.0,
        0.798, 0.0, 0.0, 0.758943, 0.246596, 0.0, 0.763131, 0.233313, 0.0,
        0.798, 0.0, 0.0, 0.763131, 0.233313, 0.0, 0.767087, 0.219959, 0.0,
        0.798, 0.0, 0.0, 0.767087, 0.219959, 0.0, 0.770809, 0.206538, 0.0,
        0.798, 0.0, 0.0, 0.770809, 0.206538, 0.0, 0.774296, 0.193054, 0.0,
        0.798, 0.0, 0.0, 0.774296, 0.193054, 0.0, 0.777547, 0.179511, 0.0,
        0.798, 0.0, 0.0, 0.777547, 0.179511, 0.0, 0.780562, 0.165914, 0.0,
        0.798, 0.0, 0.0, 0.780562, 0.165914, 0.0, 0.783338, 0.152266, 0.0,
        0.798, 0.0, 0.0, 0.783338, 0.152266, 0.0, 0.785877, 0.138571, 0.0,
        0.798, 0.0, 0.0, 0.785877, 0.138571, 0.0, 0.788175, 0.124835, 0.0,
        0.798, 0.0, 0.0, 0.788175, 0.124835, 0.0, 0.790234, 0.11106, 0.0,
        0.798, 0.0, 0.0, 0.790234, 0.11106, 0.0, 0.792052, 0.097252, 0.0,
        0.798, 0.0, 0.0, 0.792052, 0.097252, 0.0, 0.793628, 0.083414, 0.0,
        0.798, 0.0, 0.0, 0.793628, 0.083414, 0.0, 0.794963, 0.06955, 0.0,
        0.798, 0.0, 0.0, 0.794963, 0.06955, 0.0, 0.796056, 0.055666, 0.0,
        0.798, 0.0, 0.0, 0.796056, 0.055666, 0.0, 0.796906, 0.041764, 0.0,
        0.798, 0.0, 0.0, 0.796906, 0.041764, 0.0, 0.797514, 0.02785, 0.0,
        0.798, 0.0, 0.0, 0.797514, 0.02785, 0.0, 0.797878, 0.013927, 0.0,
        0.641, 0.0, 0.0, 0.616, 0.042, 0.0, 0.620162, 0.502198, 0.0,
        0.641, 0.0, 0.0, 0.620162, 0.502198, 0.0, 0.628833, 0.491298, 0.0,
        0.641, 0.0, 0.0, 0.628833, 0.491298, 0.0, 0.637311, 0.480248, 0.0,
        0.641, 0.0, 0.0, 0.637311, 0.480248, 0.0, 0.645595, 0.469053, 0.0,
        0.616, 0.042, 0.0, 0.51, 0.118038, 0.0, 0.54, 0.11, 0.0,
        0.616, 0.042, 0.0, 0.54, 0.11, 0.0, 0.57, 0.118038, 0.0,
        0.616, 0.042, 0.0, 0.57, 0.118038, 0.0, 0.591962, 0.14, 0.0,
        0.616, 0.042, 0.0, 0.591962, 0.14, 0.0, 0.6, 0.17, 0.0,
        0.616, 0.042, 0.0, 0.6, 0.17, 0.0, 0.601962, 0.33, 0.0,
        0.616, 0.042, 0.0, 0.601962, 0.33, 0.0, 0.61, 0.36, 0.0,
        0.616, 0.042, 0.0, 0.61, 0.36, 0.0, 0.611303, 0.512945, 0.0,
        0.616, 0.042, 0.0, 0.611303, 0.512945, 0.0, 0.620162, 0.502198, 0.0,
        0.48, 0.17, 0.0, 0.411, 0.68402, 0.0, 0.422875, 0.676743, 0.0,
        0.48, 0.17, 0.0, 0.422875, 0.676743, 0.0, 0.434622, 0.669259, 0.0,
        0.48, 0.17, 0.0, 0.434622, 0.669259, 0.0, 0.446236, 0.661572, 0.0,
        0.48, 0.17, 0.0, 0.446236, 0.661572, 0.0, 0.457714, 0.653684, 0.0,
        0.48, 0.17, 0.0, 0.457714, 0.653684, 0.0, 0.469052, 0.645596, 0.0,
        0.48, 0.17, 0.0, 0.469052, 0.645596, 0.0, 0.480248, 0.637311, 0.0,
        0.48, 0.17, 0.0, 0.480248, 0.637311, 0.0, 0.488038, 0.2, 0.0,
        0.616, 0.042, 0.0, 0.23, 0.042, 0.0, 0.315, 0.126699, 0.0,
        0.616, 0.042, 0.0, 0.315, 0.126699, 0.0, 0.34, 0.12, 0.0,
        0.616, 0.042, 0.0, 0.34, 0.12, 0.0, 0.365, 0.126699, 0.0,
        0.616, 0.042, 0.0, 0.365, 0.126699, 0.0, 0.383301, 0.145, 0.0,
        0.23, 0.042, 0.0, 0.29, 0.17, 0.0, 0.296699, 0.145, 0.0,
        0.23, 0.042, 0.0, 0.296699, 0.145, 0.0, 0.315, 0.126699, 0.0,
        0.58362, 0.544235, 0.0, 0.593029, 0.533966, 0.0, 0.601961, 0.39, 0.0,
        0.593029, 0.533966, 0.0, 0.602258, 0.523535, 0.0, 0.601961, 0.39, 0.0,
        0.601961, 0.39, 0.0, 0.602258, 0.523535, 0.0, 0.61, 0.36, 0.0,
        0.602258, 0.523535, 0.0, 0.611303, 0.512945, 0.0, 0.61, 0.36, 0.0,
        0.58, 0.411962, 0.0, 0.55, 0.42, 0.0, 0.554337, 0.574033, 0.0,
        0.58, 0.411962, 0.0, 0.554337, 0.574033, 0.0, 0.564271, 0.564271, 0.0,
        0.58, 0.411962, 0.0, 0.564271, 0.564271, 0.0, 0.574033, 0.554338, 0.0,
        0.58, 0.411962, 0.0, 0.574033, 0.554338, 0.0, 0.58362, 0.544235, 0.0,
        0.58, 0.411962, 0.0, 0.58362, 0.544235, 0.0, 0.601961, 0.39, 0.0,
        0.55, 0.42, 0.0, 0.52, 0.411962, 0.0, 0.523535, 0.602258, 0.0,
        0.55, 0.42, 0.0, 0.523535, 0.602258, 0.0, 0.533966, 0.59303, 0.0,
        0.55, 0.42, 0.0, 0.533966, 0.59303, 0.0, 0.544235, 0.58362, 0.0,
        0.55, 0.42, 0.0, 0.544235, 0.58362, 0.0, 0.554337, 0.574033, 0.0,
        0.51, 0.221962, 0.0, 0.488038, 0.2, 0.0, 0.49, 0.36, 0.0,
        0.488038, 0.2, 0.0, 0.491298, 0.628833, 0.0, 0.49, 0.36, 0.0,
        0.49, 0.36, 0.0, 0.491298, 0.628833, 0.0, 0.498038, 0.39, 0.0,
        0.491298, 0.628833, 0.0, 0.502197, 0.620163, 0.0, 0.498038, 0.39, 0.0,
        0.498038, 0.39, 0.0, 0.502197, 0.620163, 0.0, 0.52, 0.411962, 0.0,
        0.502197, 0.620163, 0.0, 0.512944, 0.611304, 0.0, 0.52, 0.411962, 0.0,
        0.52, 0.411962, 0.0, 0.512944, 0.611304, 0.0, 0.523535, 0.602258, 0.0,
        0.49, 0.36, 0.0, 0.498039, 0.33, 0.0, 0.51, 0.221962, 0.0,
        0.498039, 0.33, 0.0, 0.52, 0.308039, 0.0, 0.51, 0.221962, 0.0,
        0.51, 0.221962, 0.0, 0.52, 0.308039, 0.0, 0.54, 0.23, 0.0,
        0.52, 0.308039, 0.0, 0.55, 0.3, 0.0, 0.54, 0.23, 0.0,
        0.54, 0.23, 0.0, 0.55, 0.3, 0.0, 0.57, 0.221962, 0.0,
        0.55, 0.3, 0.0, 0.58, 0.308039, 0.0, 0.57, 0.221962, 0.0,
        0.57, 0.221962, 0.0, 0.58, 0.308039, 0.0, 0.591962, 0.2, 0.0,
        0.58, 0.308039, 0.0, 0.601962, 0.33, 0.0, 0.591962, 0.2, 0.0,
        0.591962, 0.2, 0.0, 0.601962, 0.33, 0.0, 0.6, 0.17, 0.0,
        0.488038, 0.2, 0.0, 0.480248, 0.637311, 0.0, 0.491298, 0.628833, 0.0,
        0.26, 0.452, 0.0, 0.216, 0.293, 0.0, 0.192, 0.332, 0.0,
        0.102, 0.178, 0.0, 0.21, 0.0, 0.0, 0.0, 0.0, 0.0,
    ];
}

const PROBABILITY_SCALE: f32 = 600.0;

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Glyph {
    HelixIn,
    Helix,
    HelixOut,
    PizzaIn,
    Pizza,
    PizzaOut,
    HelixAndPizza,
}

/// A thing that is usually still and now and then turns all the way over.
#[derive(Clone, Copy, Default)]
struct Spinner {
    spinning_p: bool,
    /// 0.0 - 1.0
    position: f32,
    /// 0.0 - 1.0, eased in and out
    position_eased: f32,
    /// Portion of the path that is eased. <= 0.5
    easement: f32,
    /// How far along the path, and it may be negative.
    speed: f32,
    /// Relative likelihood of starting to spin.
    probability: f32,
}

/// Smooth curve up, ending at slope = 1.
fn spinner_ease(x: f32) -> f32 {
    ((x / 2.0 + 1.0) * std::f32::consts::PI).cos() + 1.0
}

impl Spinner {
    fn tick(&mut self, speed: f32, button_down: bool) {
        if speed == 0.0 || button_down {
            return;
        }
        if self.spinning_p {
            self.position += self.speed;
            if self.position >= 1.0 || self.position <= 0.0 {
                self.position = 0.0;
                self.position_eased = 0.0;
                self.spinning_p = false;
            } else if self.easement > 0.0 && self.position <= self.easement {
                self.position_eased = self.easement * spinner_ease(self.position / self.easement);
            } else if self.easement > 0.0 && self.position >= 1.0 - self.easement {
                self.position_eased =
                    1.0 - self.easement * spinner_ease((1.0 - self.position) / self.easement);
            } else {
                self.position_eased = self.position;
            }
        } else if self.probability > 0.0
            && random_below((PROBABILITY_SCALE / self.probability) as i32) == 0
        {
            let ss = 0.004;
            self.spinning_p = true;
            self.position = 0.0;
            loop {
                self.speed = speed * (frand(ss / 3.0) + frand(ss / 3.0) + frand(ss / 3.0)) as f32;
                if self.speed > 0.0 {
                    break;
                }
            }
            if random() & 1 != 0 {
                self.speed = -self.speed;
                self.position = 1.0;
            }
        }
    }
}

/// Everything the shapes are built from, all of it upstream's resources.
struct Params {
    wall_facets: i32,
    bar_facets: i32,
    clockwise: bool,
    turns: f32,
    turn_spacing: f32,
    bar_spacing: f32,
    wall_height: f32,
    wall_thickness: f32,
    bar_thickness: f32,
    wall_taper: f32,
    gasket_size: f32,
    gasket_thickness: f32,
    frame_size: f32,
    frame_depth: f32,
    frame_thickness: f32,
    triangle_size: f32,
}

impl Default for Params {
    fn default() -> Params {
        Params {
            wall_facets: 360,
            bar_facets: 90,
            clockwise: false,
            turns: 0.72,
            turn_spacing: 2.3,
            bar_spacing: 0.268,
            wall_height: 0.42,
            wall_thickness: 0.12,
            bar_thickness: 0.058,
            wall_taper: 0.95,
            gasket_size: 2.0,
            gasket_thickness: 0.4,
            frame_size: 1.28,
            frame_depth: 0.01,
            frame_thickness: 0.03,
            triangle_size: 0.045,
        }
    }
}

/// `do_normal`: work the normal out from three points of a face and set it.
fn do_normal(g: &mut Gl, a: [f32; 3], b: [f32; 3], c: [f32; 3]) {
    let n = calc_normal(a, b, c);
    g.glx.normal3f(n[0], n[1], n[2]);
}

/// Calculate the angle (in radians) between two vectors.
fn vector_angle(a: [f32; 3], b: [f32; 3]) -> f32 {
    let la = (a[0] * a[0] + a[1] * a[1] + a[2] * a[2]).sqrt();
    let lb = (b[0] * b[0] + b[1] * b[1] + b[2] * b[2]).sqrt();
    if la == 0.0 || lb == 0.0 || a == b {
        return 0.0;
    }
    // avoid fp rounding error (1.000001 => sqrt error)
    let cc = ((a[0] * b[0] + a[1] * b[1] + a[2] * b[2]) / (la * lb)).min(1.0);
    cc.acos()
}

/* Make the helix */

fn make_helix(g: &mut Gl, dc: &Params, facetted: bool, wire: bool) {
    let wall_facets = dc.wall_facets / if facetted { 10 } else { 1 };
    let max_th = std::f32::consts::PI * 2.0 * dc.turns;
    let th_inc = std::f32::consts::PI * 2.0 / wall_facets as f32;

    let (mut x1, mut y1) = (1.0f32, 0.0f32);
    let (mut x1b, mut y1b) = (1.0f32, 0.0f32);
    let (mut x2, mut y2, mut x2b, mut y2b) = (0.0f32, 0.0f32, 0.0f32, 0.0f32);
    let mut z2;
    let mut h2 = 0.0f32;
    let mut h2off = 0.0f32;
    let mut z_inc = dc.turn_spacing / wall_facets as f32;

    let mut th = 0.0f32;
    let mut z1 = -(dc.turn_spacing * dc.turns / 2.0);

    let mut h1 = if dc.wall_taper > 0.0 {
        0.0
    } else {
        dc.wall_height / 2.0
    };
    let mut h1off = if dc.wall_taper > 0.0 {
        -dc.wall_height / 2.0
    } else {
        0.0
    };

    if !dc.clockwise {
        z1 = -z1;
        z_inc = -z_inc;
        h1off = -h1off;
    }

    // Upstream flips the winding four times per facet, and a winding change
    // starts a new draw call, so a three hundred and sixty facet helix would
    // be a thousand of them. The faces are collected by which way they are
    // wound instead and drawn in two runs, which is the same picture in four.
    let mut cw: Vec<([f32; 3], [f32; 3])> = Vec::new();
    let mut ccw: Vec<([f32; 3], [f32; 3])> = Vec::new();
    let mut lines: Vec<[f32; 3]> = Vec::new();

    /* Leading end-cap */
    if !wire && h1 > 0.0 {
        let n = [
            (th + std::f32::consts::FRAC_PI_2).cos(),
            (th + std::f32::consts::FRAC_PI_2).sin(),
            0.0,
        ];
        for p in [
            [x1, y1, z1 - h1 + h1off],
            [x1, y1, z1 + h1 + h1off],
            [x1b, y1b, z1 + h1 + h1off],
            [x1b, y1b, z1 - h1 + h1off],
        ] {
            ccw.push((n, p));
        }
    }

    while th + th_inc <= max_th {
        let mut thick = dc.wall_thickness;

        th += th_inc;

        x2 = th.cos();
        y2 = th.sin();
        z2 = z1 + z_inc;

        h2 = h1;
        h2off = h1off;

        if dc.wall_taper > 0.0 {
            h2off = 0.0;
            if th < dc.wall_taper {
                h2 = dc.wall_height / 2.0
                    * (std::f32::consts::FRAC_PI_2 * (1.0 - (th / dc.wall_taper))).cos();
                h2off = if dc.clockwise {
                    h2 - dc.wall_height / 2.0
                } else {
                    dc.wall_height / 2.0 - h2
                };
                if th + th_inc <= 0.0 {
                    thick = 0.0;
                } else {
                    thick *= (std::f32::consts::FRAC_PI_2 * (1.0 - (th / dc.wall_taper))).cos();
                }
            } else if th >= max_th - dc.wall_taper {
                /* edge case: always come to a point */
                h2 = if th + th_inc > max_th {
                    0.0
                } else {
                    dc.wall_height / 2.0
                        * (std::f32::consts::FRAC_PI_2 * (1.0 - ((max_th - th) / dc.wall_taper)))
                            .cos()
                };
                h2off = if dc.clockwise {
                    dc.wall_height / 2.0 - h2
                } else {
                    h2 - dc.wall_height / 2.0
                };
                if th + th_inc > max_th {
                    thick = 0.0;
                } else {
                    thick *= (std::f32::consts::FRAC_PI_2
                        * (1.0 - ((max_th - th) / dc.wall_taper)))
                        .cos();
                }
            }
        }

        x2b = x2 * (1.0 - thick);
        y2b = y2 * (1.0 - thick);

        let outer = [
            [x1, y1, z1 - h1 + h1off],
            [x1, y1, z1 + h1 + h1off],
            [x2, y2, z2 + h2 + h2off],
            [x2, y2, z2 - h2 + h2off],
        ];
        let inner = [
            [x1b, y1b, z1 - h1 + h1off],
            [x1b, y1b, z1 + h1 + h1off],
            [x2b, y2b, z2 + h2 + h2off],
            [x2b, y2b, z2 - h2 + h2off],
        ];
        let top = [
            [x2, y2, z2 + h2 + h2off],
            [x2b, y2b, z2 + h2 + h2off],
            [x1b, y1b, z1 + h1 + h1off],
            [x1, y1, z1 + h1 + h1off],
        ];
        let bottom = [
            [x1, y1, z1 - h1 + h1off],
            [x1b, y1b, z1 - h1 + h1off],
            [x2b, y2b, z2 - h2 + h2off],
            [x2, y2, z2 - h2 + h2off],
        ];

        if wire {
            for face in [outer, inner, top, bottom] {
                for i in 0..4 {
                    lines.push(face[i]);
                    lines.push(face[(i + 1) % 4]);
                }
            }
        } else {
            /* outer face */
            cw.push(([x1, y1, 0.0], outer[0]));
            cw.push(([x1, y1, 0.0], outer[1]));
            cw.push(([x2, y2, 0.0], outer[2]));
            cw.push(([x2, y2, 0.0], outer[3]));

            /* inner face */
            ccw.push(([-x1b, -y1b, 0.0], inner[0]));
            ccw.push(([-x1b, -y1b, 0.0], inner[1]));
            ccw.push(([-x2b, -y2b, 0.0], inner[2]));
            ccw.push(([-x2b, -y2b, 0.0], inner[3]));

            /* top face */
            let n = calc_normal(top[0], top[1], top[2]);
            for p in top {
                ccw.push((n, p));
            }

            /* bottom face */
            let n = calc_normal(bottom[0], bottom[1], bottom[2]);
            for p in bottom {
                ccw.push((n, p));
            }
        }

        x1 = x2;
        y1 = y2;
        x1b = x2b;
        y1b = y2b;
        z1 += z_inc;
        h1 = h2;
        h1off = h2off;
    }

    /* Trailing end-cap */
    if !wire && h2 > 0.0 {
        let n = [
            (th + std::f32::consts::FRAC_PI_2).cos(),
            (th + std::f32::consts::FRAC_PI_2).sin(),
            0.0,
        ];
        for p in [
            [x2, y2, z1 - h2 + h2off],
            [x2, y2, z1 + h2 + h2off],
            [x2b, y2b, z1 + h2 + h2off],
            [x2b, y2b, z1 - h2 + h2off],
        ] {
            cw.push((n, p));
        }
    }

    if wire {
        g.glx.begin(Shape::Lines);
        for p in lines {
            g.glx.vertex3f(p[0], p[1], p[2]);
        }
        g.glx.end();
        return;
    }
    for (facing, faces) in [(true, &cw), (false, &ccw)] {
        g.glx.front_face_cw(facing);
        g.glx.begin(Shape::Quads);
        for (n, p) in faces {
            g.glx.normal3f(n[0], n[1], n[2]);
            g.glx.vertex3f(p[0], p[1], p[2]);
        }
        g.glx.end();
    }
}

fn make_ladder(g: &mut Gl, dc: &Params, facetted: bool, wire: bool) {
    let max_th = dc.turns * std::f32::consts::PI * 2.0;
    let max_z = dc.turns * dc.turn_spacing;
    let mut z_inc = dc.bar_spacing;
    let th_inc = std::f32::consts::PI * 2.0 * (dc.bar_spacing / dc.turn_spacing);

    /* skip forward to center the bars in the helix... */
    let usable_th = max_th - dc.wall_taper;
    let usable_z = max_z / (max_th / usable_th);
    let mut nbars = (usable_z / dc.bar_spacing) as i32;

    /* always an odd number of bars */
    if nbars & 1 == 0 {
        nbars -= 1;
    }

    let used_z = (nbars - 1) as f32 * dc.bar_spacing;
    let pad_z = max_z - used_z;
    let pad_ratio = pad_z / max_z;

    let mut th = max_th * pad_ratio / 2.0;
    let mut z = -(max_z / 2.0) + (max_z * pad_ratio / 2.0);

    /* ##### WHYYYYYY */
    /* The image is not reflected across line y = -x and I don't know why. */
    th += std::f32::consts::PI * -0.035;
    z -= 0.08;

    if !dc.clockwise {
        z = -z;
        z_inc = -z_inc;
    }

    g.glx.front_face_cw(false);
    for _ in 0..nbars {
        let facets = (dc.bar_facets / if facetted { 14 } else { 1 }).max(3);
        let x = th.cos() * (1.0 - dc.wall_thickness);
        let y = th.sin() * (1.0 - dc.wall_thickness);
        tube(
            &mut g.glx,
            [x, y, z],
            [-x, -y, z],
            dc.bar_thickness,
            0.0,
            facets,
            true,
            true,
            wire,
        );
        z += z_inc;
        th += th_inc;
    }
}

/* Make the gasket */

/// The gasket's outline: radius and angle in degrees, read off the sign.
#[rustfmt::skip]
fn gasket_controls(wire: bool) -> Vec<(f32, f32)> {
    let r1a = 0.825; /* bottom of wall below upper left hole */
    let r1  = 0.916; /* 471 */
    let r2  = 0.963; /* 490 */
    let r3  = 0.960; /* 499 */
    let r4  = 1.000; /* 507 */
    let r5  = 1.080; /* 553 */
    let mut c = vec![
        (0.829, 0.0),   /* top indentation, right half */
        (0.831, 0.85),
        (0.835, 1.81),
        (0.841, 2.65),
        (0.851, 3.30),
        (0.862, 3.81),
        (0.872, 3.95),

        (r4,    4.0),   /* moving clockwise... */
        (r4,   47.0),
        (r1,   47.0),
        (r1,   53.0),
        (r2,   55.5),
        (r2,   72.3),
        (r1,   74.0),
        (r1,  100.0),
        (r3,  102.5),
        (r3,  132.0),
        (r1,  133.0),

        (r1,  180.7),
        (r2,  183.6),
        (r2,  210.0),
        (r1,  212.0),
        (r1,  223.2),
        (r5,  223.2),
        (r5,  225.0),
        (r4,  225.0),

        (r4,    316.8), /* upper left indentation */
        (0.990, 316.87),
        (0.880, 317.21),
        (0.872, 317.45),
        (0.869, 317.80),
        (0.867, 318.10),

        (0.867, 318.85),
        (0.869, 319.15),
        (0.872, 319.50),
        (0.880, 319.74),
        (0.990, 320.08),

        (r4,  338.0),
    ];
    if !wire {
        c.push((r1a, 338.0)); /* cut-out disc */
        c.push((r1a, 344.0));
    }
    c.extend_from_slice(&[
        (r4,  344.0),
        (r4,  356.0),

        (0.872, 356.05), /* top indentation, left half */
        (0.862, 356.19),
        (0.851, 356.70),
        (0.841, 357.35),
        (0.835, 358.19),
        (0.831, 359.15),
        (0.829, 360.0),
    ]);
    c
}

fn make_gasket(g: &mut Gl, dc: &Params, wire: bool) {
    let res = 360 / 8;
    let d2r = std::f32::consts::PI / 180.0;
    let thick2 = (dc.gasket_thickness / dc.gasket_size) / 2.0;

    let r0 = 0.750; /* 395 */
    let r1b = 0.867; /* center of upper left hole */
    let r1c = 0.909; /* top of wall above hole */
    let r4 = 1.000;

    let ctrl = gasket_controls(wire);

    g.glx.push_matrix();

    // Walk the outline, putting a point every eight degrees or so and
    // interpolating the radius between control points.
    let mut p0: Vec<[f32; 2]> = Vec::new();
    let mut p1: Vec<[f32; 2]> = Vec::new();
    for i in 1..ctrl.len() {
        let (from_r, from_th) = (ctrl[i - 1].0, ctrl[i - 1].1 * d2r);
        let (to_r, to_th) = (ctrl[i].0, ctrl[i].1 * d2r);

        let step = 2.0 * std::f32::consts::PI / res as f32;
        let nsteps = 1 + ((to_th - from_th) / step) as i32;

        for j in 0..nsteps + i32::from(i == ctrl.len() - 1) {
            let r = from_r + (j as f32 * (to_r - from_r) / nsteps as f32);
            let th = from_th + (j as f32 * (to_th - from_th) / nsteps as f32);

            let cth = th.cos() * dc.gasket_size;
            let sth = th.sin() * dc.gasket_size;

            p0.push([r0 * cth, r0 * sth]); /* inner ring */
            p1.push([r * cth, r * sth]); /* outer ring */
        }
    }
    let npoints = p0.len();

    /* normals for the outer ring */
    let mut normals = vec![[0.0f32; 2]; npoints];
    for i in 1..npoints {
        let a = [p1[i - 1][0], p1[i - 1][1], 0.0];
        let b = [p1[i][0], p1[i][1], 0.0];
        let c = [p1[i][0], p1[i][1], 1.0];
        let n = calc_normal(a, b, c);
        normals[i - 1] = [n[0], n[1]];
    }

    g.glx.rotate(-90.0, 0.0, 1.0, 0.0);
    g.glx.rotate(180.0, 0.0, 0.0, 1.0);

    if wire {
        for k in 0..2 {
            let z = -thick2 + k as f32 * thick2 * 2.0;
            for ring in [&p0, &p1] {
                g.glx.begin(Shape::LineLoop);
                for p in ring {
                    g.glx.vertex3f(p[0], p[1], z);
                }
                g.glx.end();
            }
        }
        g.glx.begin(Shape::Lines);
        for i in 0..npoints {
            /* inside rim */
            g.glx.vertex3f(p0[i][0], p0[i][1], -thick2);
            g.glx.vertex3f(p0[i][0], p0[i][1], thick2);
            /* outside rim */
            g.glx.vertex3f(p1[i][0], p1[i][1], -thick2);
            g.glx.vertex3f(p1[i][0], p1[i][1], thick2);
        }
        g.glx.end();
    } else {
        /* top and bottom */
        for (cw, z, nz) in [(true, -thick2, -1.0f32), (false, thick2, 1.0)] {
            g.glx.front_face_cw(cw);
            g.glx.normal3f(0.0, 0.0, nz);
            g.glx.begin(Shape::QuadStrip);
            for i in 0..npoints {
                g.glx.vertex3f(p0[i][0], p0[i][1], z);
                g.glx.vertex3f(p1[i][0], p1[i][1], z);
            }
            g.glx.end();
        }

        /* inside edge */
        g.glx.front_face_cw(true);
        g.glx.begin(Shape::QuadStrip);
        for p in &p0 {
            g.glx.normal3f(-p[0], -p[1], 0.0);
            g.glx.vertex3f(p[0], p[1], thick2);
            g.glx.vertex3f(p[0], p[1], -thick2);
        }
        g.glx.end();

        /* outside edge */
        g.glx.front_face_cw(false);
        g.glx.begin(Shape::Quads);
        for i in 0..npoints - 1 {
            let ia = if i == 0 { npoints - 2 } else { i - 1 };
            let iz = if i == npoints - 2 { 0 } else { i + 1 };
            let (x, y) = (p1[i][0], p1[i][1]);
            let (xz, yz) = (p1[iz][0], p1[iz][1]);

            let [nxa, nya] = normals[ia]; /* normal of [i-1 - i] face */
            let [nx, ny] = normals[i]; /* normal of [i - i+1] face */
            let [nxz, nyz] = normals[iz]; /* normal of [i+1 - i+2] face */

            let anglea = vector_angle([nx, ny, 0.0], [nxa, nya, 0.0]);
            let anglez = vector_angle([nx, ny, 0.0], [nxz, nyz, 0.0]);
            // Where two faces meet at more than this, leave the corner
            // sharp; otherwise average the normals and let it curve.
            let pointy = 0.6;

            if anglea > pointy {
                g.glx.normal3f(nx, ny, 0.0);
            } else {
                g.glx.normal3f((nxa + nx) / 2.0, (nya + ny) / 2.0, 0.0);
            }
            g.glx.vertex3f(x, y, thick2);
            g.glx.vertex3f(x, y, -thick2);

            if anglez > pointy {
                g.glx.normal3f(nx, ny, 0.0);
            } else {
                g.glx.normal3f((nx + nxz) / 2.0, (ny + nyz) / 2.0, 0.0);
            }
            g.glx.vertex3f(xz, yz, -thick2);
            g.glx.vertex3f(xz, yz, thick2);
        }
        g.glx.end();
    }

    /* Fill in the upper left hole... */
    {
        let mut q = [[0.0f32; 2]; 4];
        for (k, deg) in [338.0f32, 344.0].into_iter().enumerate() {
            let th = deg * d2r;
            q[k * 2] = [
                r1c * th.cos() * dc.gasket_size,
                r1c * th.sin() * dc.gasket_size,
            ];
            q[k * 2 + 1] = [
                r4 * th.cos() * dc.gasket_size,
                r4 * th.sin() * dc.gasket_size,
            ];
        }

        if !wire {
            /* front and back walls */
            for (cw, z, nz) in [(true, -thick2, -1.0f32), (false, thick2, 1.0)] {
                g.glx.normal3f(0.0, 0.0, nz);
                g.glx.front_face_cw(cw);
                g.glx.begin(Shape::Quads);
                for k in [0, 1, 3, 2] {
                    g.glx.vertex3f(q[k][0], q[k][1], z);
                }
                g.glx.end();
            }
        }

        /* top wall */
        g.glx.front_face_cw(true);
        g.glx
            .begin(if wire { Shape::LineLoop } else { Shape::Quads });
        g.glx.normal3f(q[1][0], q[1][1], 0.0);
        g.glx.vertex3f(q[1][0], q[1][1], thick2);
        g.glx.normal3f(q[3][0], q[3][1], 0.0);
        g.glx.vertex3f(q[3][0], q[3][1], thick2);
        g.glx.vertex3f(q[3][0], q[3][1], -thick2);
        g.glx.normal3f(q[1][0], q[1][1], 0.0);
        g.glx.vertex3f(q[1][0], q[1][1], -thick2);
        g.glx.end();

        /* Now make a donut. */
        {
            let nsteps = if wire { 12 } else { 64 };
            let dr0 = 0.04;
            let dr1 = 0.070;

            g.glx.push_matrix();

            let th = ((339.0 + 343.0) / 2.0) * d2r;
            g.glx.translate(
                r1b * th.cos() * dc.gasket_size,
                r1b * th.sin() * dc.gasket_size,
                0.0,
            );

            let mut d0: Vec<[f32; 2]> = Vec::new();
            let mut d1: Vec<[f32; 2]> = Vec::new();
            for i in 0..nsteps {
                let th = 2.0 * std::f32::consts::PI * i as f32 / nsteps as f32;
                let cth = th.cos() * dc.gasket_size;
                let sth = th.sin() * dc.gasket_size;
                d0.push([dr0 * cth, dr0 * sth]);
                d1.push([dr1 * cth, dr1 * sth]);
            }
            d0.push(d0[0]);
            d1.push(d1[0]);

            if wire {
                for z in [-thick2, thick2] {
                    g.glx.begin(Shape::LineLoop);
                    for p in &d0 {
                        g.glx.vertex3f(p[0], p[1], z);
                    }
                    g.glx.end();
                }
            } else {
                for (cw, z, nz) in [(true, -thick2, -1.0f32), (false, thick2, 1.0)] {
                    g.glx.front_face_cw(cw);
                    g.glx.normal3f(0.0, 0.0, nz);
                    g.glx.begin(Shape::QuadStrip);
                    for i in 0..d0.len() {
                        g.glx.vertex3f(d0[i][0], d0[i][1], z);
                        g.glx.vertex3f(d1[i][0], d1[i][1], z);
                    }
                    g.glx.end();
                }
            }

            /* inside edge */
            g.glx.front_face_cw(true);
            g.glx
                .begin(if wire { Shape::Lines } else { Shape::QuadStrip });
            for p in &d0 {
                g.glx.normal3f(-p[0], -p[1], 0.0);
                g.glx.vertex3f(p[0], p[1], thick2);
                g.glx.vertex3f(p[0], p[1], -thick2);
            }
            g.glx.end();

            g.glx.pop_matrix();
        }
    }

    /* Attach the bottom-right dingus... */
    {
        let w = 0.05;
        let h = 0.19;

        g.glx.rotate(49.5, 0.0, 0.0, 1.0);
        g.glx.scale(dc.gasket_size, dc.gasket_size, 1.0);
        /* midway between the inner ring and the wall, which is r1 */
        g.glx.translate(0.0, (r0 + 0.916) / 2.0, 0.0);

        /* buried box */
        if !wire {
            g.glx.front_face_cw(false);
            g.glx.begin(Shape::Quads);
            for (n, quad) in [
                (
                    [0.0, 0.0, -1.0],
                    [(-1, -1, -1), (-1, 1, -1), (1, 1, -1), (1, -1, -1)],
                ),
                (
                    [1.0, 0.0, 0.0],
                    [(1, -1, -1), (1, 1, -1), (1, 1, 1), (1, -1, 1)],
                ),
                (
                    [0.0, 0.0, 1.0],
                    [(1, -1, 1), (1, 1, 1), (-1, 1, 1), (-1, -1, 1)],
                ),
                (
                    [-1.0f32, 0.0, 0.0],
                    [(-1, -1, 1), (-1, 1, 1), (-1, 1, -1), (-1, -1, -1)],
                ),
            ] {
                g.glx.normal3f(n[0], n[1], n[2]);
                for (sx, sy, sz) in quad {
                    g.glx
                        .vertex3f(sx as f32 * w / 2.0, sy as f32 * h / 2.0, sz as f32 * thick2);
                }
            }
            g.glx.end();
        }

        let mut c: Vec<[f32; 2]> = Vec::new();
        let mut th = if wire { 0.0 } else { -0.1f32 };
        let step = std::f32::consts::PI / if wire { 5.0 } else { 32.0 };
        while th <= std::f32::consts::PI + 0.1 {
            c.push([w / 2.0 * th.cos(), w / 2.0 * th.sin()]);
            th += step;
        }

        /* the four half-discs that cap the ends, front and back */
        for (nz, z, cw_in, cw_out) in [(-1.0f32, -thick2, true, false), (1.0, thick2, false, true)]
        {
            g.glx.normal3f(0.0, 0.0, nz);
            for (sign, cw) in [(1.0f32, cw_in), (-1.0, cw_out)] {
                g.glx.front_face_cw(cw);
                g.glx.begin(if wire {
                    Shape::LineStrip
                } else {
                    Shape::TriangleFan
                });
                if !wire {
                    g.glx.vertex3f(0.0, sign * h / 2.0, z);
                }
                for p in &c {
                    g.glx.vertex3f(p[0], sign * (h / 2.0 + p[1]), z);
                }
                g.glx.end();
            }
        }

        /* inside and outside curves */
        for (sign, cw) in [(1.0f32, false), (-1.0, true)] {
            g.glx.front_face_cw(cw);
            g.glx
                .begin(if wire { Shape::Lines } else { Shape::QuadStrip });
            for p in &c {
                g.glx.normal3f(p[0], sign * p[1], 0.0);
                g.glx.vertex3f(p[0], sign * (h / 2.0 + p[1]), thick2);
                g.glx.vertex3f(p[0], sign * (h / 2.0 + p[1]), -thick2);
            }
            g.glx.end();
        }
    }

    g.glx.pop_matrix();
}

fn make_frame(g: &mut Gl, dc: &Params, wire: bool) {
    let corner_cut = 0.5;

    g.glx.push_matrix();
    g.glx.rotate(90.0, 0.0, 1.0, 0.0);
    g.glx.scale(
        4.0 * dc.frame_size,
        4.0 * dc.frame_size,
        4.0 * dc.frame_size,
    );

    let x = [
        -dc.frame_thickness,
        -dc.frame_thickness * corner_cut,
        0.0,
        0.5 - dc.triangle_size,
        0.5,
        0.5 + dc.triangle_size,
        1.0,
        1.0 + dc.frame_thickness * corner_cut,
        1.0 + dc.frame_thickness,
    ];
    let y = [
        -dc.frame_thickness,
        -dc.frame_thickness * corner_cut,
        0.0,
        dc.triangle_size,
    ];

    /* front and back */
    g.glx.translate(-0.5, -0.5, dc.frame_depth / 4.0);
    if !wire {
        for j in 0..2 {
            if j == 1 {
                g.glx.translate(0.0, 0.0, -dc.frame_depth / 2.0);
            }
            g.glx.front_face_cw(j == 0);
            for _ in 0..4 {
                g.glx.normal3f(0.0, 0.0, if j == 1 { -1.0 } else { 1.0 });
                g.glx.begin(Shape::QuadStrip);
                for (a, b) in [
                    (x[0], y[1]),
                    (x[0], y[2]),
                    (x[1], y[0]),
                    (x[1], y[2]),
                    (x[3], y[0]),
                    (x[3], y[2]),
                    (x[4], y[0]),
                    (x[4], y[3]),
                    (x[5], y[0]),
                    (x[5], y[2]),
                    (x[7], y[0]),
                    (x[7], y[2]),
                    (x[8], y[1]),
                    (x[8], y[2]),
                ] {
                    g.glx.vertex3f(a, b, 0.0);
                }
                g.glx.end();
                g.glx.translate(0.5, 0.5, 0.0);
                g.glx.rotate(90.0, 0.0, 0.0, 1.0);
                g.glx.translate(-0.5, -0.5, 0.0);
            }
        }
    }

    /* ledges */
    g.glx.front_face_cw(false);
    for _ in 0..4 {
        g.glx.normal3f(0.0, 1.0, 0.0);
        g.glx
            .begin(if wire { Shape::Lines } else { Shape::QuadStrip });
        for (a, b) in [
            (x[2], y[2]),
            (x[3], y[2]),
            (x[4], y[3]),
            (x[5], y[2]),
            (x[6], y[2]),
        ] {
            g.glx.vertex3f(a, b, 0.0);
            g.glx.vertex3f(a, b, dc.frame_depth / 2.0);
        }
        g.glx.end();

        g.glx.normal3f(0.0, -1.0, 0.0);
        g.glx
            .begin(if wire { Shape::LineLoop } else { Shape::Quads });
        g.glx.vertex3f(x[7], y[0], 0.0);
        g.glx.vertex3f(x[7], y[0], dc.frame_depth / 2.0);
        g.glx.vertex3f(x[1], y[0], dc.frame_depth / 2.0);
        g.glx.vertex3f(x[1], y[0], 0.0);
        g.glx.end();

        g.glx.normal3f(1.0, -1.0, 0.0);
        g.glx
            .begin(if wire { Shape::LineLoop } else { Shape::Quads });
        g.glx.vertex3f(x[8], y[1], 0.0);
        g.glx.vertex3f(x[8], y[1], dc.frame_depth / 2.0);
        g.glx.vertex3f(x[7], y[0], dc.frame_depth / 2.0);
        g.glx.vertex3f(x[7], y[0], 0.0);
        g.glx.end();

        if wire {
            g.glx.normal3f(0.0, 1.0, 0.0);
            for j in 0..2 {
                g.glx.begin(Shape::LineStrip);
                for (a, b) in [
                    (x[2], y[2]),
                    (x[3], y[2]),
                    (x[4], y[3]),
                    (x[5], y[2]),
                    (x[6], y[2]),
                ] {
                    g.glx.vertex3f(a, b, j as f32 * dc.frame_depth / 2.0);
                }
                g.glx.end();
            }
        }

        g.glx.translate(0.5, 0.5, 0.0);
        g.glx.rotate(90.0, 0.0, 0.0, 1.0);
        g.glx.translate(-0.5, -0.5, 0.0);
    }

    g.glx.pop_matrix();
}

/// Make some pizza.
///
/// Upstream fills the slice with the GLU tessellator, which is not here and
/// is not in its own OpenGL ES build either; that build carries the triangles
/// the tessellator produced once, and so does this.
fn make_pizza(g: &mut Gl, dc: &Params, facetted: bool, wire: bool) {
    let topfaces = if facetted { 48 } else { 120 };
    let thick2 = (dc.gasket_thickness / dc.gasket_size) / 4.0;

    g.glx.push_matrix();

    // Stand the slice up to face the camera, the way the gasket does, and
    // put its point at the middle of the ring.
    let s = 1.9;
    g.glx.rotate(180.0, 0.0, 0.0, 1.0);
    g.glx.scale(s, s, s);
    g.glx.rotate(90.0, 0.0, 1.0, 0.0);
    g.glx.translate(-0.53, 0.0, 0.0);
    g.glx.rotate(-30.0, 0.0, 0.0, 1.0);

    if !wire {
        for (cw, dz, nz) in [(true, thick2, 1.0f32), (false, -thick2, -1.0)] {
            g.glx.translate(0.0, 0.0, dz);
            g.glx.normal3f(0.0, 0.0, nz);
            g.glx.front_face_cw(cw);
            g.glx.begin(Shape::Triangles);
            for v in pizza::TRIANGLES.chunks_exact(3) {
                g.glx.vertex3f(v[0], v[1], v[2]);
            }
            g.glx.end();
            g.glx.translate(0.0, 0.0, -dz);
        }
    }

    /* Compute the crust */
    let step = std::f32::consts::PI * 2.0 / 6.0 / topfaces as f32;
    let mut points: Vec<[f32; 2]> = Vec::new();
    let mut th = 0.0f32;
    for _ in 0..topfaces {
        points.push([th.cos() * 0.861, th.sin() * 0.861]);
        th += step;
    }
    for _ in 0..topfaces {
        points.push([th.cos(), th.sin()]);
        th -= step;
    }

    /* Draw the rim of the crust */
    g.glx.front_face_cw(false);
    g.glx
        .begin(if wire { Shape::Lines } else { Shape::QuadStrip });
    for i in 0..topfaces * 2 {
        let p = points[i];
        if i == 0 || i == topfaces * 2 - 1 {
            g.glx.normal3f(0.0, -1.0, 0.0);
        } else if i == topfaces - 1 || i == topfaces {
            g.glx.normal3f(0.0, 1.0, 0.0);
        } else {
            let q = points[i - 1];
            do_normal(
                g,
                [q[0], q[1], thick2],
                [p[0], p[1], thick2],
                [p[0], p[1], -thick2],
            );
        }
        g.glx.vertex3f(p[0], p[1], -thick2);
        g.glx.vertex3f(p[0], p[1], thick2);
    }
    g.glx.vertex3f(points[0][0], points[0][1], -thick2);
    g.glx.vertex3f(points[0][0], points[0][1], thick2);
    g.glx.end();

    if wire {
        for z in [-thick2, thick2] {
            g.glx.begin(Shape::LineStrip);
            for p in points.iter().take(topfaces * 2) {
                g.glx.vertex3f(p[0], p[1], z);
            }
            g.glx.vertex3f(points[0][0], points[0][1], z);
            g.glx.end();
        }
    } else {
        /* Draw the top and the bottom of the crust */
        for (cw, z, nz) in [(true, -thick2, -1.0f32), (false, thick2, 1.0)] {
            g.glx.front_face_cw(cw);
            g.glx.begin(Shape::QuadStrip);
            g.glx.normal3f(0.0, 0.0, nz);
            for i in 0..topfaces {
                let ii = topfaces + (topfaces - i - 1);
                g.glx.vertex3f(points[i][0], points[i][1], z);
                g.glx.vertex3f(points[ii][0], points[ii][1], z);
            }
            g.glx.end();
        }
    }

    g.glx.pop_matrix();
}

struct Logo {
    trackball: Trackball,
    button_down: bool,
    dc: Params,
    color: [f32; 4],
    speed: f32,
    mode: Glyph,
    anim_state: Glyph,
    anim_ratio: f32,

    gasket_spinnerx: Spinner,
    gasket_spinnery: Spinner,
    gasket_spinnerz: Spinner,
    scene_spinnerx: Spinner,
    scene_spinnery: Spinner,
    helix_spinnerz: Spinner,
    pizza_spinnery: Spinner,
    pizza_spinnerz: Spinner,
    frame_spinner: Spinner,

    /// Frames left of drawing the wireframe over the solid.
    wire_overlay: i32,
    wire: bool,

    helix_list: u32,
    helix_list_wire: u32,
    helix_list_facetted: u32,
    pizza_list: u32,
    pizza_list_wire: u32,
    pizza_list_facetted: u32,
    gasket_list: u32,
    gasket_list_wire: u32,
    frame_list: u32,
    frame_list_wire: u32,
}

/// When one of a pair starts to spin, give the other one a turn to start too.
fn link_spinners(s0: &Spinner, s1: &mut Spinner, speed: f32, down: bool) {
    if s0.spinning_p && !s1.spinning_p {
        let op = s1.probability;
        s1.probability = PROBABILITY_SCALE;
        s1.tick(speed, down);
        s1.probability = op;
    }
}

impl Hack3d for Logo {
    fn draw(&mut self, g: &mut Gl) -> u32 {
        let wire = self.wire;
        let specular = [0.8, 0.8, 0.8, 1.0];
        let shininess = 50.0;

        if !wire && self.wire_overlay == 0 && random_below((PROBABILITY_SCALE / 0.2) as i32) == 0 {
            self.wire_overlay = random_below(200) + random_below(200) + random_below(200);
        }

        let (speed, down) = (self.speed, self.button_down);
        for s in [
            &mut self.gasket_spinnerx,
            &mut self.gasket_spinnery,
            &mut self.gasket_spinnerz,
            &mut self.helix_spinnerz,
            &mut self.pizza_spinnery,
            &mut self.pizza_spinnerz,
            &mut self.scene_spinnerx,
            &mut self.scene_spinnery,
            &mut self.frame_spinner,
        ] {
            s.tick(speed, down);
        }
        let sx = self.scene_spinnerx;
        link_spinners(&sx, &mut self.scene_spinnery, speed, down);

        match self.anim_state {
            Glyph::Helix => {
                if self.mode == Glyph::HelixAndPizza
                    && random_below((PROBABILITY_SCALE / 0.2) as i32) == 0
                {
                    self.anim_state = Glyph::HelixOut;
                }
            }
            Glyph::Pizza => {
                if self.mode == Glyph::HelixAndPizza
                    && random_below((PROBABILITY_SCALE / 0.2) as i32) == 0
                {
                    self.anim_state = Glyph::PizzaOut;
                }
            }
            _ => {
                self.anim_ratio += 0.1 * self.speed;
                if self.anim_ratio >= 1.0 {
                    self.anim_ratio = 0.0;
                    self.anim_state = match self.anim_state {
                        Glyph::HelixOut => Glyph::PizzaIn,
                        Glyph::PizzaIn => Glyph::Pizza,
                        Glyph::PizzaOut => Glyph::HelixIn,
                        _ => Glyph::Helix,
                    };
                }
            }
        }

        let pizza_p = matches!(
            self.anim_state,
            Glyph::Pizza | Glyph::PizzaIn | Glyph::PizzaOut
        );

        g.glx.depth_test(true);
        g.glx.cull_face(true);
        g.glx.clear();

        g.glx.push_matrix();
        g.glx.scale(1.8, 1.8, 1.8);
        g.glx.color3f(self.color[0], self.color[1], self.color[2]);

        /* Draw frame before trackball rotation */
        {
            let p = self.frame_spinner.position_eased.abs();
            let size = if p > 0.5 { 1.0 - p } else { p };
            let scale = 1.0 + (size * 10.0);
            g.glx.push_matrix();
            g.glx.rotate(90.0, 1.0, 0.0, 0.0);
            g.glx.rotate(90.0, 0.0, 0.0, 1.0);
            g.glx.scale(1.0, scale, scale);
            if wire {
                g.glx.lighting(false);
                g.glx.call_list(self.frame_list_wire);
            } else if self.wire_overlay != 0 {
                g.glx.call_list(self.frame_list);
                g.glx.lighting(false);
                g.glx.color3f(self.color[0], self.color[1], self.color[2]);
                g.glx.call_list(self.frame_list_wire);
                g.glx.lighting(true);
            } else {
                g.glx.call_list(self.frame_list);
            }
            g.glx.pop_matrix();
        }

        let m = self.trackball.matrix();
        g.glx.mult_matrix(m);

        g.glx.rotate(90.0, 1.0, 0.0, 0.0);
        g.glx.rotate(90.0, 0.0, 0.0, 1.0);

        g.glx
            .rotate(360.0 * self.scene_spinnerx.position_eased, 0.0, 1.0, 0.0);
        g.glx
            .rotate(360.0 * self.scene_spinnery.position_eased, 0.0, 0.0, 1.0);

        g.glx.push_matrix();

        g.glx
            .rotate(360.0 * self.gasket_spinnerx.position_eased, 0.0, 1.0, 0.0);
        g.glx
            .rotate(360.0 * self.gasket_spinnery.position_eased, 0.0, 0.0, 1.0);
        g.glx
            .rotate(360.0 * self.gasket_spinnerz.position_eased, 1.0, 0.0, 0.0);

        // While the wireframe is on top, the solid underneath it goes black
        // and matt so that the lines read.
        let (gcolor, specular, shininess) = if self.wire_overlay != 0 {
            ([0.0, 0.0, 0.0, 1.0], [0.0, 0.0, 0.0, 1.0], 0.0)
        } else {
            (self.color, specular, shininess)
        };
        g.glx.material_ambient_diffuse(gcolor);
        g.glx.material_specular(specular);
        g.glx.material_shininess(shininess);

        if wire {
            g.glx.lighting(false);
            g.glx.call_list(self.gasket_list_wire);
        } else if self.wire_overlay != 0 {
            g.glx.call_list(self.gasket_list);
            g.glx.lighting(false);
            g.glx.color3f(self.color[0], self.color[1], self.color[2]);
            g.glx.call_list(self.gasket_list_wire);
            g.glx.lighting(true);
            g.glx.material_ambient_diffuse(gcolor);
        } else {
            g.glx.call_list(self.gasket_list);
        }
        g.glx.pop_matrix();

        if pizza_p {
            g.glx
                .rotate(360.0 * self.pizza_spinnery.position_eased, 1.0, 0.0, 0.0);
            g.glx
                .rotate(360.0 * self.pizza_spinnerz.position_eased, 0.0, 0.0, 1.0);
        } else {
            g.glx
                .rotate(360.0 * self.helix_spinnerz.position_eased, 0.0, 0.0, 1.0);
        }

        let scale = match self.anim_state {
            Glyph::PizzaIn | Glyph::HelixIn => self.anim_ratio,
            Glyph::PizzaOut | Glyph::HelixOut => 1.0 - self.anim_ratio,
            _ => 1.0,
        }
        .max(0.001);
        g.glx.scale(scale, scale, scale);

        if wire {
            g.glx.lighting(false);
            g.glx.call_list(if pizza_p {
                self.pizza_list_wire
            } else {
                self.helix_list_wire
            });
        } else if self.wire_overlay != 0 {
            g.glx.call_list(if pizza_p {
                self.pizza_list_facetted
            } else {
                self.helix_list_facetted
            });
            g.glx.lighting(false);
            g.glx.color3f(self.color[0], self.color[1], self.color[2]);
            g.glx.call_list(if pizza_p {
                self.pizza_list_wire
            } else {
                self.helix_list_wire
            });
            g.glx.lighting(true);
        } else {
            g.glx.call_list(if pizza_p {
                self.pizza_list
            } else {
                self.helix_list
            });
        }

        g.glx.pop_matrix();

        if self.wire_overlay > 0 {
            self.wire_overlay -= 1;
        }

        g.res.int("delay").max(0) as u32
    }

    fn reshape(&mut self, g: &mut Gl, width: i32, height: i32) {
        let h = height.max(1) as f32 / width as f32;
        let persp = 64.0;
        let pos = 13.0;

        g.glx.viewport(0, 0, width, height);

        g.glx.matrix_mode_projection();
        g.glx.load_identity();
        g.glx.perspective(persp, 1.0 / h, 1.0, 100.0);

        g.glx.matrix_mode_modelview();
        g.glx.load_identity();
        g.glx
            .look_at([0.0, 0.0, pos], [0.0, 0.0, 0.0], [0.0, 1.0, 0.0]);

        let s = if width < height {
            width as f32 / height.max(1) as f32
        } else {
            1.0
        };
        g.glx.scale(s, s, s);
    }

    fn event(&mut self, g: &mut Gl, event: &XEvent) -> bool {
        let handled = self.trackball.event(event, g.width(), g.height());
        self.button_down = self.trackball.button_down();
        handled
    }
}

fn make(g: &mut Gl) -> Logo {
    let wire = g.res.bool("wireframe");
    let dc = Params::default();

    if !wire {
        // A light off to one side, which is what gives the gasket's rim its
        // shape: it is a flat ring otherwise.
        g.glx.light_position(0, -3.0, 1.0, 3.0, 0.0);
        g.glx.cull_face(true);
        g.glx.lighting(true);
        g.glx.light_enable(0, true);
        g.glx.depth_test(true);
    }

    let mode = match g.res.string("mode") {
        "helix" => Glyph::Helix,
        "pizza" => Glyph::Pizza,
        _ => Glyph::HelixAndPizza,
    };

    let mut st = Logo {
        trackball: Trackball::new(),
        button_down: false,
        color: [0.0, 0.666_666_7, 0.0, 1.0], /* #00AA00 */
        speed: g.res.float("speed") as f32,
        mode,
        anim_state: if mode == Glyph::HelixAndPizza {
            if random() & 1 != 0 {
                Glyph::Helix
            } else {
                Glyph::Pizza
            }
        } else {
            mode
        },
        anim_ratio: 0.0,
        gasket_spinnerx: Spinner {
            probability: 0.1,
            easement: 0.08,
            ..Spinner::default()
        },
        gasket_spinnery: Spinner {
            probability: 0.1,
            easement: 0.08,
            ..Spinner::default()
        },
        gasket_spinnerz: Spinner {
            probability: 1.0,
            easement: 0.08,
            ..Spinner::default()
        },
        scene_spinnerx: Spinner {
            probability: 0.1,
            easement: 0.1,
            ..Spinner::default()
        },
        scene_spinnery: Spinner {
            probability: 0.0,
            easement: 0.1,
            ..Spinner::default()
        },
        helix_spinnerz: Spinner {
            probability: 0.6,
            easement: 0.2,
            ..Spinner::default()
        },
        pizza_spinnery: Spinner {
            probability: 0.6,
            easement: 0.2,
            ..Spinner::default()
        },
        pizza_spinnerz: Spinner {
            probability: 0.6,
            easement: 0.2,
            ..Spinner::default()
        },
        /* start the frame off-screen */
        frame_spinner: Spinner {
            probability: 5.0,
            easement: 0.2,
            spinning_p: true,
            position: 0.3,
            speed: 0.001,
            ..Spinner::default()
        },
        wire_overlay: 0,
        wire,
        dc,
        helix_list: 0,
        helix_list_wire: 0,
        helix_list_facetted: 0,
        pizza_list: 0,
        pizza_list_wire: 0,
        pizza_list_facetted: 0,
        gasket_list: 0,
        gasket_list_wire: 0,
        frame_list: 0,
        frame_list_wire: 0,
    };

    if st.speed > 0.0 {
        /* start off with the gasket in motion */
        st.gasket_spinnerz.spinning_p = true;
        st.gasket_spinnerz.speed = 0.002 * if random() & 1 != 0 { 1.0 } else { -1.0 } * st.speed;
    }

    let helix_rot = 147.0;
    for (list, facetted, w) in [
        (&mut st.helix_list, false, false),
        (&mut st.helix_list_wire, true, true),
        (&mut st.helix_list_facetted, true, false),
    ] {
        let id = g.glx.gen_lists(1);
        *list = id;
        g.glx.push_matrix();
        g.glx.new_list(id);
        // Upstream leaves the rotation out of the wireframe list, with a
        // "wtf?" beside it; the wireframe is only ever drawn on top of the
        // solid, where it would be out of step. It is put back here.
        g.glx.rotate(helix_rot, 0.0, 0.0, 1.0);
        make_ladder(g, &st.dc, facetted, w);
        make_helix(g, &st.dc, facetted, w);
        g.glx.rotate(180.0, 0.0, 0.0, 1.0);
        make_helix(g, &st.dc, facetted, w);
        g.glx.end_list();
        g.glx.pop_matrix();
    }

    for (list, facetted, w) in [
        (&mut st.pizza_list, false, false),
        (&mut st.pizza_list_wire, true, true),
        (&mut st.pizza_list_facetted, true, false),
    ] {
        let id = g.glx.gen_lists(1);
        *list = id;
        g.glx.new_list(id);
        make_pizza(g, &st.dc, facetted, w);
        g.glx.end_list();
    }

    for (list, w) in [
        (&mut st.gasket_list, false),
        (&mut st.gasket_list_wire, true),
    ] {
        let id = g.glx.gen_lists(1);
        *list = id;
        g.glx.new_list(id);
        make_gasket(g, &st.dc, w);
        g.glx.end_list();
    }

    for (list, w) in [(&mut st.frame_list, false), (&mut st.frame_list_wire, true)] {
        let id = g.glx.gen_lists(1);
        *list = id;
        g.glx.new_list(id);
        make_frame(g, &st.dc, w);
        g.glx.end_list();
    }

    /* When drawing both solid and wireframe objects, make sure the wireframe
    actually shows up! */
    g.glx.polygon_offset(Some((1.0, 1.0)));

    let (w, h) = (g.width(), g.height());
    st.reshape(g, w, h);
    st
}

fn init(g: &mut Gl) -> Box<dyn Hack3d> {
    Box::new(make(g))
}

const DEFAULTS: &[&str] = &[
    "*delay:      25000",
    "*showFPS:    False",
    "*wireframe:  False",
    "*speed:      1.0",
    "*mode:       both",
];

const MODES: &[SelectItem] = &[
    SelectItem {
        value: "both",
        label: "DNA Lounge and DNA Pizza logos",
    },
    SelectItem {
        value: "helix",
        label: "DNA Lounge logo",
    },
    SelectItem {
        value: "pizza",
        label: "DNA Pizza logo",
    },
];

const OPTS: &[Opt] = &[
    Opt::slider("delay", "Frame rate", 0.0, 100_000.0, 1000.0, 0, "25000").inverted(),
    Opt::select("mode", "Logo", MODES, "both"),
    Opt::boolean("wireframe", "Wireframe", "false"),
];

pub static DEF: SaverDef = SaverDef {
    slug: "dnalogo",
    label: "DNA Logo",
    defaults: DEFAULTS,
    opts: OPTS,
    about: About {
        author: "Jamie Zawinski",
        year: "2001",
        video: Some("https://www.youtube.com/watch?v=B7I5A7E3SP0"),
        blurb: "DNA Lounge. Restaurant, bar, nightclub, cafe. Est. 1985. \
                375 Eleventh Street, San Francisco.",
    },
};

/// The saver's entry point, and the one function its wasm chunk exports.
pub fn start(args: StartArgs) -> Runner3d {
    Runner3d::start(&DEF, init, args)
}

#[cfg(not(target_arch = "wasm32"))]
pub static SAVER: Saver3d = Saver3d { def: &DEF, start };

#[cfg(test)]
mod tests {
    use super::*;

    fn display() -> Gl {
        crate::runtime::ya_rand_init(20260812);
        let mut g = Gl::for_test(640, 480);
        for d in DEFAULTS {
            if let Some((k, v)) = d.split_once(':') {
                g.res.set(k.trim().trim_start_matches(['.', '*']), v.trim());
            }
        }
        g
    }

    /// Everything one of the shape functions drew, as plain vertices.
    fn drew(f: impl FnOnce(&mut Gl, &Params)) -> (Vec<[f32; 3]>, usize) {
        let mut g = Gl::for_test(640, 480);
        g.glx.start_frame(640, 480);
        f(&mut g, &Params::default());
        let frame = g.glx.frame();
        (
            frame.vertices.iter().map(|v| v.pos).collect(),
            frame.batches.len(),
        )
    }

    #[test]
    fn the_gasket_is_a_ring_of_the_right_size() {
        let (v, _) = drew(|g, dc| make_gasket(g, dc, false));
        assert!(v.len() > 3000, "{}", v.len());

        // The recorder keeps vertices in the space they were named in, before
        // the matrix that stands the gasket up, so the ring is in x and y and
        // its thickness is in z.
        let span = |i: usize| {
            let lo = v.iter().fold(f32::MAX, |a, p| a.min(p[i]));
            let hi = v.iter().fold(f32::MIN, |a, p| a.max(p[i]));
            (lo, hi)
        };
        let (lo, hi) = span(2);
        assert!(hi - lo < 0.5, "the ring is not flat: {lo} to {hi}");
        for i in [0, 1] {
            let (lo, hi) = span(i);
            // Radius two, and the one lobe that reaches out to r5 = 1.08.
            assert!((3.8..4.4).contains(&(hi - lo)), "axis {i}: {lo} to {hi}");
        }

        // Every point is either on the inner ring at r0 = 0.75 or somewhere
        // between there and the outer lobe, and none is at the centre. The
        // donut in the upper left hole is drawn about its own middle, so it
        // is not counted.
        let mut inner = 0;
        for p in &v {
            let r = (p[0] * p[0] + p[1] * p[1]).sqrt() / 2.0;
            if (r - 0.75).abs() < 0.02 {
                inner += 1;
            }
        }
        assert!(inner > 500, "only {inner} points on the inner ring");
    }

    #[test]
    fn the_helix_turns_the_way_it_is_told() {
        for clockwise in [false, true] {
            let dc = Params {
                clockwise,
                ..Params::default()
            };
            let mut g = Gl::for_test(640, 480);
            g.glx.start_frame(640, 480);
            make_helix(&mut g, &dc, false, false);
            let v: Vec<[f32; 3]> = g.glx.frame().vertices.iter().map(|p| p.pos).collect();
            assert!(v.len() > 4000, "{}", v.len());

            // It is a wall wrapped round a cylinder of radius one, minus its
            // thickness, and it is as long in z as the turn spacing says.
            for p in &v {
                let r = (p[0] * p[0] + p[1] * p[1]).sqrt();
                assert!((0.85..=1.001).contains(&r), "radius {r}");
            }
            let lo = v.iter().fold(f32::MAX, |a, p| a.min(p[2]));
            let hi = v.iter().fold(f32::MIN, |a, p| a.max(p[2]));
            // The turns, plus the height of the wall standing off each end.
            let want = dc.turn_spacing * dc.turns + dc.wall_height;
            assert!(
                (hi - lo - want).abs() < 0.05,
                "{} of z for {want} of turns",
                hi - lo
            );
        }
    }

    #[test]
    fn the_pizza_is_a_slice_with_a_crust() {
        let (v, _) = drew(|g, dc| make_pizza(g, dc, false, false));
        assert!(v.len() > 1000, "{}", v.len());

        // A sixth of a disc of radius one, so every point is inside the unit
        // circle and in the first sextant.
        for p in &v {
            let r = (p[0] * p[0] + p[1] * p[1]).sqrt();
            assert!(r <= 1.001, "radius {r}");
            assert!(p[0] >= -0.001, "{p:?} is behind the slice");
            assert!(p[1] >= -0.001, "{p:?} is below the slice");
        }
        // The crust is the outermost ring, and the filling stops short of it.
        let outer = v.iter().filter(|p| {
            let r = (p[0] * p[0] + p[1] * p[1]).sqrt();
            r > 0.99
        });
        assert!(outer.count() > 100, "no crust");
    }

    #[test]
    fn a_spinner_turns_once_and_stops() {
        crate::runtime::ya_rand_init(20260812);
        let mut s = Spinner {
            probability: 1.0,
            easement: 0.1,
            ..Spinner::default()
        };
        let mut turns = 0;
        let mut was = false;
        let mut most = 0.0f32;
        for _ in 0..200_000 {
            s.tick(1.0, false);
            if s.spinning_p {
                most = most.max(s.position_eased);
                assert!(
                    (0.0..=1.0).contains(&s.position_eased),
                    "{}",
                    s.position_eased
                );
            }
            if was && !s.spinning_p {
                turns += 1;
            }
            was = s.spinning_p;
        }
        assert!(turns > 10, "only {turns} turns");
        assert!(most > 0.9, "it never got all the way round: {most}");
        // Eased: the first step off zero is much smaller than a step in the
        // middle would be.
        let mut s = Spinner {
            probability: 0.0,
            easement: 0.1,
            spinning_p: true,
            speed: 0.01,
            ..Spinner::default()
        };
        s.tick(1.0, false);
        assert!(s.position_eased < s.position / 2.0, "{}", s.position_eased);
    }

    #[test]
    fn the_logo_is_drawn_and_the_pizza_takes_its_turn() {
        let mut g = display();
        let mut st = make(&mut g);
        st.reshape(&mut g, 640, 480);

        let mut seen = Vec::new();
        let mut most = 0;
        for _ in 0..4000 {
            g.glx.start_frame(640, 480);
            st.draw(&mut g);
            most = most.max(g.glx.frame().batches.len());
            if !seen.contains(&st.anim_state) {
                seen.push(st.anim_state);
            }
            assert!(!g.glx.frame().batches.is_empty());
        }
        // It gets from the helix to the pizza and back.
        assert!(seen.contains(&Glyph::Helix), "{seen:?}");
        assert!(seen.contains(&Glyph::Pizza), "{seen:?}");
        assert!(most < 6000, "{most}");

        // The wireframe overlay comes on about one frame in three thousand,
        // so rather than wait for it, turn it on and see that it draws more
        // than the solid alone did and then counts itself down.
        g.glx.start_frame(640, 480);
        st.draw(&mut g);
        let solid = g.glx.frame().batches.len();
        st.wire_overlay = 5;
        g.glx.start_frame(640, 480);
        st.draw(&mut g);
        assert!(g.glx.frame().batches.len() > solid, "no lines were added");
        assert_eq!(st.wire_overlay, 4);
    }
}
