//! Port of `hacks/bumps.c`.
//!
//! ```text
//! Bumps, Copyright (c) 2002, 2006 Shane Smit <CodeWeaver@DigitalLoom.org>
//!
//! Permission to use, copy, modify, distribute, and sell this software and its
//! documentation for any purpose is hereby granted without fee, provided that
//! the above copyright notice appear in all copies and that both that
//! copyright notice and this permission notice appear in supporting
//! documentation.  No representations are made about the suitability of this
//! software for any purpose.  It is provided "as is" without express or
//! implied warranty.
//!
//! Module: "bumps.c"
//! Tab Size: 4
//!
//! Description:
//!  This is typical bump-mapping.  The actual bump map is generated by a screen
//!  grab.  The light source is represented by a spotlight of random color. This
//!  spotlight randomly traverses the bump map in a sinus pattern.
//!
//!  Essentially, it 3D-izes your desktop, based on color intensity.
//!
//! Modification History:
//!  [10/01/1999] - Shane Smit: Creation
//!  [10/08/1999] - Shane Smit: Port to C. (Ick)
//!  [03/08/2002] - Shane Smit: New movement code.
//!  [09/12/2002] - Shane Smit: MIT-SHM XImages.
//!                             Thanks to Kennett Galbraith <http://www.Alpha-II.com/>
//!                             for code optimization.
//!  [10/09/2016] - Dave Odell: Updated for new xshm.c.
//!                             Y2K compliance.
//! ```
//!
//! Bump mapping, and all of it happens in two lines: the height difference to
//! the pixel on the right and the one below becomes a surface normal, that
//! normal picks a point in a precomputed disc of light, and the brightness
//! there is the colour. Everything else is preparation. The heights come from
//! the intensity of a loaded picture, softened once so the ridges are not
//! pixel-stepped, and the light wanders under a random acceleration that turns
//! back towards the middle whenever it reaches an edge.

#[cfg(not(target_arch = "wasm32"))]
use crate::runtime::Saver;
use crate::runtime::color::{XColor, parse_color};
use crate::runtime::{
    About, Dpy, Gc, ImageLoad, Opt, Pixel, Runner, SaverDef, Screenhack, StartArgs, XEvent, random,
    screenhack_event_helper,
};

/// Upstream's `RANDOM()`: the C library's `random()` is already this wide, so
/// the mask only matters here.
fn rnd() -> i32 {
    (random() & 0x7FFF_FFFF) as i32
}

/// The light, and where it is drifting.
#[derive(Default)]
struct SpotLight {
    /// Brightness indices, `light_diameter` square, bright in the middle and
    /// black outside the inscribed circle.
    light_map: Vec<u8>,
    falloff_diameter: i32,
    falloff_radius: i32,
    light_diameter: i32,
    light_radius: i32,
    accel_x: f32,
    accel_y: f32,
    accel_max: f32,
    velocity_x: f32,
    velocity_y: f32,
    velocity_max: f32,
    x_pos: f32,
    y_pos: f32,
}

struct State {
    gc: Gc,
    colors: Vec<Pixel>,
    /// Kept as upstream's count rather than as the length of `colors`, because
    /// the light map is built against it.
    ncolors: i32,
    win_width: i32,
    win_height: i32,
    /// One height per pixel of the window.
    bump_map: Vec<u16>,
    spot: SpotLight,
    soften: i32,
    invert: bool,
    delay: u32,
    duration: f64,
    start_time: f64,
    img_loader: Option<ImageLoad>,
    loading: bool,
}

impl State {
    /// A phong shade: a ramp from near-black to the base colour, bent by a
    /// power curve so most of the range is spent near the top.
    fn set_palette(&mut self, d: &Dpy) {
        let mut base = XColor::from_rgb16(
            (rnd() % 0xFFFF) as u16,
            (rnd() % 0xFFFF) as u16,
            (rnd() % 0xFFFF) as u16,
        );

        // Make one channel full intensity to avoid dark spotlights.
        match rnd() % 3 {
            0 => base.red = 0xFFFF,
            1 => base.green = 0xFFFF,
            _ => base.blue = 0xFFFF,
        }

        let spec = d.res.string("color");
        if !spec.eq_ignore_ascii_case("random")
            && let Some(p) = parse_color(spec)
        {
            base = XColor::from_pixel(p);
        }

        let n = d.res.int("colorcount").clamp(2, 128) - 1;
        let shade = |c: u16, i: i32| -> u16 {
            let f = i as f64 / n as f64;
            let v = (c as f64 / n as f64) * i as f64 + ((0xFFFF - c) as f64).powf(f);
            v as u16
        };
        self.colors = (0..=n)
            .map(|i| {
                XColor::from_rgb16(
                    shade(base.red, i),
                    shade(base.green, i),
                    shade(base.blue, i),
                )
                .pixel
            })
            .collect();
        self.ncolors = n + 1;
    }

    /// The light map: white in the middle, falling off linearly to the edge of
    /// the inscribed circle and black beyond it.
    fn create_spot_light(&mut self, diameter: i32) {
        let ncolors = self.ncolors;
        let s = &mut self.spot;
        s.falloff_diameter = diameter;
        s.falloff_radius = s.falloff_diameter / 2;
        s.light_diameter = diameter / 2;
        s.light_radius = s.light_diameter / 2;

        s.light_map = vec![0u8; (s.light_diameter * s.light_diameter) as usize];
        let r = s.light_radius as f64;
        let mut o = 0usize;
        for dy in -s.light_radius..s.light_radius {
            for dx in -s.light_radius..s.light_radius {
                let dist =
                    ((dx as f64 + 0.5).powi(2) + (dy as f64 + 0.5).powi(2)).sqrt() / r.max(1e-9);
                // Never quite reaches `ncolors`, because the centre of a pixel
                // is never exactly on the centre of the disc: the truncation
                // is what keeps this inside the palette.
                s.light_map[o] = if dist <= 1.0 {
                    (ncolors as f64 - dist * (ncolors - 1) as f64) as u8
                } else {
                    0
                };
                o += 1;
            }
        }

        s.accel_x = 0.0;
        s.accel_y = 0.0;
        s.velocity_x = if rnd() % 2 != 0 {
            s.velocity_max
        } else {
            -s.velocity_max
        };
        s.velocity_y = if rnd() % 2 != 0 {
            s.velocity_max
        } else {
            -s.velocity_max
        };
    }

    /// Where the light goes next. Away from an edge it is pushed by a random
    /// force; within half a falloff of one it is pushed back in.
    fn calc_light_pos(&mut self) {
        let (w, h) = (self.win_width as f32, self.win_height as f32);
        let s = &mut self.spot;

        let gravity = if s.x_pos < s.falloff_radius as f32 {
            1.0
        } else if s.x_pos > w - s.falloff_radius as f32 {
            -1.0
        } else {
            ((rnd() % 201) as f32 / 100.0) - 1.0
        };
        s.accel_x = (s.accel_x + gravity * (s.accel_max / 5.0)).clamp(-s.accel_max, s.accel_max);
        s.velocity_x = (s.velocity_x + s.accel_x).clamp(-s.velocity_max, s.velocity_max);
        s.x_pos += s.velocity_x;

        let gravity = if s.y_pos < s.falloff_radius as f32 {
            1.0
        } else if s.y_pos > h - s.falloff_radius as f32 {
            -1.0
        } else {
            ((rnd() % 201) as f32 / 100.0) - 1.0
        };
        s.accel_y = (s.accel_y + gravity * (s.accel_max / 5.0)).clamp(-s.accel_max, s.accel_max);
        s.velocity_y = (s.velocity_y + s.accel_y).clamp(-s.velocity_max, s.velocity_max);
        s.y_pos += s.velocity_y;
    }

    fn start_load(&mut self, d: &mut Dpy) {
        self.img_loader = d.load_image_async_simple(None);
        self.loading = true;
        if self.img_loader.is_none() {
            self.image_arrived(d);
        }
    }

    /// Upstream loads into an off-screen pixmap and grabs the heights out of
    /// that; the channel here draws into the window instead, so read the
    /// heights straight off it and then paint the window out.
    fn image_arrived(&mut self, d: &mut Dpy) {
        self.build_bump_map(d);
        self.loading = false;
        self.start_time = d.time;

        // Upstream sets the window background to the darkest colour of the
        // palette and clears, so the picture never shows.
        let (w, h) = (self.win_width, self.win_height);
        self.gc.set_foreground(self.colors[0]);
        d.win().fill_rectangle(&self.gc, 0, 0, w, h);
    }

    /// Intensity becomes height. `soften` runs of the blur below take the
    /// maximum height down, so the scale is pushed up to compensate first.
    fn build_bump_map(&mut self, d: &mut Dpy) {
        let (w, h) = (self.win_width, self.win_height);

        let mut soften_multiplier = 1.0f64;
        for _ in 0..self.soften {
            soften_multiplier *= 1.0 + (1.0 / 3.0);
        }
        let mut max_height = (self.spot.light_radius as f64 * soften_multiplier) as u16;
        if w > 2560 || h > 2560 {
            max_height = max_height.wrapping_mul(2); // Retina displays.
        }
        let averager = if max_height != 0 {
            (3 * 0xFFFF) / max_height as u32
        } else {
            0
        };

        self.bump_map = vec![0u16; (w * h) as usize];
        for y in 0..h {
            for x in 0..w {
                let c = XColor::from_pixel(d.win_ref().get_pixel(x, y));
                let sum = c.red as u32 + c.green as u32 + c.blue as u32;
                let v = sum.checked_div(averager).unwrap_or(0) as u16;
                // Funny, it is actually the "else" that inverts the bump map.
                self.bump_map[(y * w + x) as usize] = if self.invert {
                    v
                } else {
                    max_height.wrapping_sub(v)
                };
            }
        }

        for _ in 0..self.soften {
            self.soften_bump_map();
        }
    }

    /// Soften the bump map, to avoid pixelated-looking ridges.
    ///
    /// ```text
    /// |-----|-----|-----|
    /// |  0% |12.5%|  0% |  The adjacent pixels are averaged together
    /// |-----|-----|-----|  first.  Then than value is averaged with
    /// |12.5%| 50% |12.5%|  the pixel is question. This essentially weights
    /// |-----|-----|-----|  each pixel as shown on the left.
    /// |  0% |12.5%|  0% |
    /// |-----|-----|-----|
    /// ```
    fn soften_bump_map(&mut self) {
        let (w, h) = (self.win_width as usize, self.win_height as usize);
        let mut temp = vec![0u16; w * h];
        for y in 0..h {
            for x in 0..w {
                let o = y * w + x;
                if y == 0 || y + 1 == h || x == 0 || x + 1 == w {
                    continue;
                }
                let mut n = self.bump_map[o - w] as u32;
                n += self.bump_map[o + 1] as u32;
                n += self.bump_map[o + w] as u32;
                n += self.bump_map[o - 1] as u32;
                n >>= 2;
                n += self.bump_map[o] as u32;
                n >>= 1;
                temp[o] = n as u16;
            }
        }
        self.bump_map = temp;
    }

    /// This is where we slap down some pixels.
    fn execute(&mut self, d: &mut Dpy) {
        self.calc_light_pos();

        let (w, h) = (self.win_width, self.win_height);
        let s = &self.spot;
        let far = s.falloff_diameter - s.light_radius;
        let dark = self.colors[0];

        // Offset to upper left hand corner.
        let light_x_pos = (s.x_pos - s.falloff_radius as f32) as i32;
        let light_y_pos = (s.y_pos - s.falloff_radius as f32) as i32;

        let mut screen_y = light_y_pos;
        let mut light_y = -s.light_radius;
        while light_y < far {
            if screen_y >= h {
                break;
            }
            if screen_y >= 0 {
                let mut screen_x = light_x_pos;
                let mut light_x = -s.light_radius;
                while light_x < far {
                    if screen_x >= w {
                        break;
                    }
                    if screen_x >= 0 {
                        let p = if screen_y == 0
                            || screen_y >= h - 2
                            || screen_x == 0
                            || screen_x >= w - 2
                        {
                            dark
                        } else {
                            // That is right folks, all the magic of bump
                            // mapping occurs in these two lines. (Kinda
                            // disappointing, is it not?)
                            let o = (screen_y * w + screen_x) as usize;
                            let nx =
                                (self.bump_map[o + 1] as i32 - self.bump_map[o] as i32) + light_x;
                            let ny = (self.bump_map[o + w as usize] as i32
                                - self.bump_map[o] as i32)
                                + light_y;

                            if nx < 0 || nx >= s.light_diameter || ny < 0 || ny >= s.light_diameter
                            {
                                dark
                            } else {
                                let c = s.light_map[(ny * s.light_diameter + nx) as usize] as usize;
                                self.colors[c.min(self.colors.len() - 1)]
                            }
                        };
                        d.win().put_pixel(screen_x, screen_y, p);
                    }
                    screen_x += 1;
                    light_x += 1;
                }
            }
            screen_y += 1;
            light_y += 1;
        }
    }

    /// Size and velocity are a function of window size, so it appears the same
    /// at 100x60 as it does at 3200x1200.
    fn create(&mut self, d: &mut Dpy) {
        let (w, h) = (d.width(), d.height());
        self.win_width = w;
        self.win_height = h;
        self.spot.x_pos = w as f32 / 2.0;
        self.spot.y_pos = h as f32 / 2.0;
        self.spot.velocity_max = w.min(h) as f32 / 140.0;
        self.spot.accel_max = self.spot.velocity_max / 10.0;

        // jwz: sometimes we get tearing if this lands on the wrong boundary;
        // constraining it to be a multiple of 8 seems to fix it.
        let diameter = ((w.min(h) / 2) + 7) / 8 * 8;

        self.set_palette(d);
        self.create_spot_light(diameter);
        self.start_load(d);
    }
}

fn init(d: &mut Dpy) -> Box<dyn Screenhack> {
    let mut st = State {
        gc: Gc::default(),
        colors: Vec::new(),
        ncolors: 0,
        win_width: 1,
        win_height: 1,
        bump_map: Vec::new(),
        spot: SpotLight::default(),
        soften: d.res.int("soften").clamp(0, 255),
        invert: d.res.bool("invert"),
        delay: d.res.int("delay").max(0) as u32,
        duration: d.res.int("duration").max(1) as f64,
        start_time: 0.0,
        img_loader: None,
        loading: false,
    };
    st.create(d);
    Box::new(st)
}

impl Screenhack for State {
    fn draw(&mut self, d: &mut Dpy) -> u32 {
        if self.loading {
            self.img_loader = d.load_image_async_simple(self.img_loader.take());
            if self.img_loader.is_none() {
                self.image_arrived(d);
            }
            return self.delay;
        }

        // A fresh picture every so often. Upstream draws one more frame off
        // the old heights before the new one lands, and so does this.
        if self.start_time + self.duration < d.time {
            self.start_load(d);
        }

        self.execute(d);
        self.delay
    }

    fn reshape(&mut self, d: &mut Dpy, _width: i32, _height: i32) {
        // Upstream does nothing here, which leaves the bump map at the old
        // size. Here the heights are indexed by window position, so they have
        // to be rebuilt, which means asking for the picture again.
        self.create(d);
    }

    fn event(&mut self, _d: &mut Dpy, event: &XEvent) -> bool {
        if screenhack_event_helper(event) {
            self.start_time = f64::NEG_INFINITY;
            return true;
        }
        false
    }
}

const DEFAULTS: &[&str] = &[
    ".background: black",
    ".foreground: white",
    "*fpsSolid: true",
    "*color: random",
    "*colorcount: 64",
    "*delay: 30000",
    "*duration: 120",
    "*soften: 1",
    "*invert: FALSE",
];

const OPTS: &[Opt] = &[
    Opt::slider("delay", "Frame rate", 0.0, 100_000.0, 1000.0, 0, "30000").inverted(),
    Opt::slider("duration", "Duration", 10.0, 600.0, 10.0, 0, "120"),
];

pub static DEF: SaverDef = SaverDef {
    slug: "bumps",
    label: "Bumps",
    defaults: DEFAULTS,
    opts: OPTS,
    about: About {
        author: "Shane Smit",
        year: "1999",
        video: Some("https://www.youtube.com/watch?v=IV7D-NYRCiU"),
        blurb: "A spotlight roams across an embossed version of a loaded image.",
    },
};

/// The saver's entry point, and the one function its wasm chunk exports.
pub fn start(args: StartArgs) -> Runner {
    Runner::start(&DEF, init, args)
}

#[cfg(not(target_arch = "wasm32"))]
pub static SAVER: Saver = Saver { def: &DEF, start };
