dx := `which -a dx | grep dioxus | head -1`

dev:
    {{dx}} serve

build:
    {{dx}} build --release

check:
    cargo check --target wasm32-unknown-unknown

fmt:
    cargo fmt

clippy:
    cargo clippy --target wasm32-unknown-unknown -- -D warnings
