# Standalone build for the published repo. Generated by
# platform/tangled/publish/gen-project.nu; edit that template, not this file.
#
# The build, the devshell and its hooks, the formatter and the nixpkgs this
# resolves against are shared with every other repo published from the
# monorepo, and live in the nix-project flake. It is callable, so what is
# particular to this project is all that is left to say.
{
  description = "A CLI tool to transcode H.264/H.265 video to AV1 using h264-decode, h265-decode, and rav1e";

  inputs.project.url = "github:overby-me/nix-project";

  outputs = inputs:
    inputs.project ./. {
      name = "h26xtoav1";
      description = "A CLI tool to transcode H.264/H.265 video to AV1 using h264-decode, h265-decode, and rav1e";
      subdir = "h26xtoav1";
    };
}
