#!/usr/bin/env nu

# Generate a standalone flake and CI workflow for every published project.
#
# A published repo is a filtered copy of one directory, so it cannot use the
# monorepo's default.nix: that is a flakelight module the root flake imports,
# and it reaches for ../../nix/lib. Without something of its own, a clone is
# cargo-only and has no CI.
#
# One template covers every project because the flake reads Cargo.toml itself
# with builtins.fromTOML, so nothing needs to be restated per project. Both
# files are inert inside the monorepo: nothing imports the flake, and Tangled
# reads workflows from a repo root rather than from rust/<name>/.
#
#   nu gen-standalone.nu            # write them
#   nu gen-standalone.nu --check    # fail if any is missing or stale

# subdir is "" for the usual one-directory project, whose crate sits at the
# repo root. A project with a sibling path dependency is published as several
# directories instead, so that `path = "../pcre2"` still resolves, and then
# the crate to build is one level down.
def flake-text [
    name: string
    description: string
    nixpkgs_rev: string
    subdir: string = ""
]: nothing -> string {
    let at = if ($subdir | is-empty) { "." } else { $"./($subdir)" }
    let in_subdir = if ($subdir | is-empty) { "" } else {
        # Both are needed and they do different jobs: cargoRoot tells the
        # setup hook where Cargo.lock and the vendor config belong,
        # buildAndTestSubdir tells the build hook where to run cargo. They
        # happen to be the same directory here.
        $"
        # The repo root holds several directories so the crate's sibling path
        # dependencies resolve; the crate itself is one level down.
        cargoRoot = \"($subdir)\";
        buildAndTestSubdir = \"($subdir)\";
"
    }
    $"# Standalone build for the published repo. Generated by
# tangled/publish/gen-standalone.nu; edit that template, not this file.
#
# Deliberately not the monorepo's default.nix, which is a flakelight module
# the root flake imports and which reaches for ../../nix/lib, so it means
# nothing in a clone. This builds from plain nixpkgs instead.
{
  description = \"($description)\";

  # Pinned to the same revision the monorepo resolves, so every published\n  # repo builds against identical nixpkgs and they cannot drift apart. Change\n  # it by re-running the generator after a monorepo flake update, never here.\n  inputs.nixpkgs.url = \"github:NixOS/nixpkgs/($nixpkgs_rev)\";

  outputs = {
    self,
    nixpkgs,
  }: let
    systems = [\"x86_64-linux\" \"aarch64-linux\" \"aarch64-darwin\"];
    forAllSystems = f: nixpkgs.lib.genAttrs systems \(system: f nixpkgs.legacyPackages.${system}\);

    # Read the crate's own manifest rather than restating it here. A workspace
    # root has no [package], and baseNameOf ./. would give the store path, so
    # the repo name is baked in as the fallback.
    cargoToml = builtins.fromTOML \(builtins.readFile ($at)/Cargo.toml\);
    package = cargoToml.package or {};
    pname = package.name or \"($name)\";
    version = package.version or \"0.1.0\";
  in {
    packages = forAllSystems \(pkgs: {
      ${pname} = pkgs.rustPlatform.buildRustPackage {
        inherit pname version;
        src = ./.;
        cargoLock = {
          lockFile = ($at)/Cargo.lock;
          allowBuiltinFetchGit = true;
        };
($in_subdir)
        meta = {
          description = \"($description)\";
          license = pkgs.lib.licenses.mit;
        };
      };
      default = self.packages.${pkgs.stdenv.hostPlatform.system}.${pname};
    }\);

    devShells = forAllSystems \(pkgs: {
      default = pkgs.mkShell {
        inputsFrom = [self.packages.${pkgs.stdenv.hostPlatform.system}.${pname}];
        packages = with pkgs; [cargo rustc rust-analyzer clippy rustfmt];
      };
    }\);

    checks = forAllSystems \(pkgs: {
      build = self.packages.${pkgs.stdenv.hostPlatform.system}.${pname};
    }\);

    formatter = forAllSystems \(pkgs: pkgs.alejandra\);
  };
}
"
}

const CI_TEXT = "# CI for the published repo. Generated by tangled/publish/gen-standalone.nu.
#
# Inert inside the monorepo: Tangled reads .tangled/workflows from a repo's
# root, and here this sits under rust/<name>/. It becomes the published
# repo's CI once the directory is filtered out on its own.
clone:
  depth: 1
  skip: false
  submodules: false
dependencies:
  - git
  - nix
engine: microvm
image: nixos
steps:
  - command: |-
      nix --extra-experimental-features \"nix-command flakes\" \\
        flake check --print-build-logs
    name: nix flake check
when:
  - branch: '**'
    event:
      - push
"

# A pointer back to the monorepo, for a reader who arrives at a published
# repo and would otherwise open a pull request that the next sync destroys.
#
# josh ships README.md verbatim, so the published README is this one. The
# wording therefore has to be true read from either side, which is why it
# says where development happens rather than "you are looking at a mirror".
const BANNER_BEGIN = "<!-- publish:begin (generated by tangled/publish/gen-standalone.nu) -->"
const BANNER_END = "<!-- publish:end -->"

def banner-text [name: string, path: string, github: string]: nothing -> string {
    let mono = "https://tangled.org/overby.me/overby.me"
    $"($BANNER_BEGIN)
> Part of the [overby.me monorepo]\(($mono)), where this lives in
> [`($path)`]\(($mono)/tree/main/($path)) and where all development happens.
>
> It is also published on its own, as
> [tangled.org/overby.me/($name)]\(https://tangled.org/overby.me/($name)) and
> [github.com/($github)/($name)]\(https://github.com/($github)/($name)). Both
> are read-only mirrors, rebuilt from the monorepo with
> [josh]\(https://github.com/josh-project/josh): a commit made to either is
> overwritten by the next sync, so please open issues and pull requests on the
> monorepo.
($BANNER_END)"
}

# Insert or refresh the banner, after the title so the README still opens with
# its own heading.
def with-banner [readme: string, banner: string]: nothing -> string {
    let stripped = if ($readme | str contains $BANNER_BEGIN) {
        let head = ($readme | split row $BANNER_BEGIN | first)
        let tail = ($readme | split row $BANNER_END | skip 1 | str join $BANNER_END)
        $"($head)($tail | str trim -l -c "\n")"
    } else { $readme }

    let lines = ($stripped | lines)
    let title_at = ($lines | enumerate | where {|l| $l.item | str starts-with "# " } | get -o 0.index)
    if $title_at == null {
        $"($banner)\n\n($stripped)"
    } else {
        let before = ($lines | first ($title_at + 1) | str join "\n")
        let after = ($lines | skip ($title_at + 1) | str join "\n" | str trim -l -c "\n")
        $"($before)\n\n($banner)\n\n($after)"
    }
}

def main [--check, --github: string = "overby-me"]: nothing -> nothing {
    let here = ($env.FILE_PWD | default ".")
    let root = ($here | path dirname | path dirname)
    let projects = (open ($here | path join "projects.nuon"))

    # One source of truth for nixpkgs: whatever the monorepo already resolved.
    # Sharing the lock file itself would mean mapping it into every published
    # repo, and one `nix flake update` would then become N commits across N
    # repos forever. Pinning the revision gets the same synchronisation with
    # no shared surface.
    # --raw | from json: nushell does not treat .lock as JSON on its own.
    let nixpkgs_rev = (
        open --raw ($root | path join "flake.lock") | from json | get nodes.nixpkgs.locked.rev
    )
    print $"pinning nixpkgs ($nixpkgs_rev | str substring 0..9) for ($projects | length) projects"


    mut missing = []
    for p in $projects {
        let dir = ($root | path join $p.path)
        let flake = ($dir | path join "flake.nix")
        let ci = ($dir | path join ".tangled" "workflows" "ci.yml")

        # The description is the one thing worth taking from the monorepo's
        # own module, so the two do not drift apart.
        let default_nix = ($dir | path join "default.nix")
        let description = if ($default_nix | path exists) {
            let hits = (open $default_nix | lines | where {|l| $l =~ 'description = "' })
            if ($hits | is-empty) { $"A Rust rewrite, published from a monorepo" } else {
                # Unescape what default.nix escaped, then re-escape for the
                # generated string: one description contains quotes.
                $hits | first
                | str replace -r '.*description = "' ''
                | str replace -r '";.*' ''
                | str replace -a '\"' '"'
                | str replace -a '"' '\"'
            }
        } else { "A Rust rewrite, published from a monorepo" }

        # A project with sibling path dependencies publishes as several
        # directories, so its crate lands one level down under its own name.
        let subdir = if (($p | get -o deps | default []) | is-empty) { "" } else {
            $p.path | path basename
        }
        let want_flake = (flake-text $p.name $description $nixpkgs_rev $subdir)
        if $check {
            if not ($flake | path exists) { $missing = ($missing | append $p.name) }
            continue
        }
        $want_flake | save -f $flake
        mkdir ($dir | path join ".tangled" "workflows")
        $CI_TEXT | save -f $ci

        let readme = ($dir | path join "README.md")
        let banner = if ($readme | path exists) {
            let now = (open --raw $readme)
            let want = (with-banner $now (banner-text $p.name $p.path $github))
            if $want != $now { $want | save -f $readme; " + README banner" } else { "" }
        } else { "" }
        print $"  ($p.name): flake.nix + .tangled/workflows/ci.yml($banner)"
    }

    if $check and not ($missing | is-empty) {
        error make {msg: $"missing standalone flake for: ($missing | str join ', ')"}
    }
}
