#!/usr/bin/env nu

# Generate a standalone flake and CI workflow for every published project.
#
# A published repo is a filtered copy of one directory, so it cannot use the
# monorepo's default.nix: that is a flakelight module the root flake imports,
# and it reaches for ../../nix/lib. Without something of its own, a clone is
# cargo-only and has no CI.
#
# One template covers every project because the flake reads Cargo.toml itself
# with builtins.fromTOML, so nothing needs to be restated per project. Both
# files are inert inside the monorepo: nothing imports the flake, and Tangled
# reads workflows from a repo root rather than from rust/<name>/.
#
#   nu gen-standalone.nu            # write them
#   nu gen-standalone.nu --check    # fail if any is missing or stale

# subdir is "" for the usual one-directory project, whose crate sits at the
# repo root. A project with a sibling path dependency is published as several
# directories instead, so that `path = "../pcre2"` still resolves, and then
# the crate to build is one level down.
# subdir is "" for the usual one-directory project, whose crate sits at the
# repo root. A project with a sibling path dependency is published as several
# directories instead, so that `path = "../pcre2"` still resolves, and then
# the crate to build is one level down.
def flake-text [
    name: string
    description: string
    nixpkgs_rev: string
    subdir: string = ""
    native: list<string> = []
    build: list<string> = []
    check: bool = true
]: nothing -> string {
    # Most projects are pure Rust and need none of this. The few that link
    # against a C library declare it in projects.nuon, because parsing it out
    # of default.nix would mean telling the main package apart from the test
    # fixtures beside it, which are the majority of what is declared there.
    #
    # flakelight callPackages the package function, so a dependency is named
    # once, as an argument, and used from there.
    let pkg_args = (["rustPlatform"] | append $native | append $build | uniq)
    let native_line = if ($native | is-empty) { "" } else {
        $"\n          nativeBuildInputs = [($native | str join ' ')];"
    }
    let build_line = if ($build | is-empty) { "" } else {
        $"\n          buildInputs = [($build | str join ' ')];"
    }
    let check_line = if $check { "" } else {
        "\n          # Tests need network access or a running server.\n          doCheck = false;"
    }
    let extra_shell = if (($native | append $build) | is-empty) { "" } else {
        $"\n          ++ \(with pkgs; [(($native | append $build) | str join ' ')]\)"
    }
    let at = if ($subdir | is-empty) { "." } else { $"./($subdir)" }
    let in_subdir = if ($subdir | is-empty) { "" } else {
        # Both are needed and they do different jobs: cargoRoot tells the
        # setup hook where Cargo.lock and the vendor config belong,
        # buildAndTestSubdir tells the build hook where to run cargo. They
        # happen to be the same directory here.
        $"\n          # The repo root holds several directories so the crate's sibling path\n          # dependencies resolve; the crate itself is one level down.\n          cargoRoot = \"($subdir)\";\n          buildAndTestSubdir = \"($subdir)\";"
    }
    $"# Standalone build for the published repo. Generated by
# tangled/publish/gen-standalone.nu; edit that template, not this file.
#
# Deliberately not the monorepo's default.nix. That one is a flakelight module
# too, but the root flake imports it and it reaches for ../../nix/lib, so it
# means nothing in a clone. This is the same shape, standing on its own.
{
  description = \"($description)\";

  inputs = {
    # Pinned to the same revision the monorepo resolves, so every published
    # repo builds against identical nixpkgs and they cannot drift apart.
    # Change it by re-running the generator, never here.
    nixpkgs.url = \"github:NixOS/nixpkgs/($nixpkgs_rev)\";

    # The monorepo is a flakelight tree, so its published pieces are too.
    flakelight = {
      url = \"github:accelbread/flakelight\";
      inputs.nixpkgs.follows = \"nixpkgs\";
    };

    git-hooks = {
      url = \"github:cachix/git-hooks.nix\";
      inputs.nixpkgs.follows = \"nixpkgs\";
    };
  };

  outputs = inputs: let
    # Read the crate's own manifest rather than restating it here. A workspace
    # root has no [package], and baseNameOf ./. would give the store path, so
    # the repo name is baked in as the fallback.
    cargoToml = builtins.fromTOML \(builtins.readFile ($at)/Cargo.toml\);
    cargoPackage = cargoToml.package or {};
    name = cargoPackage.name or \"($name)\";

    # The same gates in every published repo, so a contributor who has only
    # this one is held to what the monorepo holds it to. Generated from a
    # shared template rather than pulled from a common repo of ours: an input
    # would make entering this shell depend on a second repo of ours, and the
    # point is that this one stands alone. Entering the shell installs them.
    hooksFor = pkgs:
      inputs.git-hooks.lib.${pkgs.stdenv.hostPlatform.system}.run {
        src = ./.;
        package = pkgs.prek;
        hooks = {
          rustfmt.enable = true;
          clippy.enable = true;
          typos.enable = true;
          ripsecrets.enable = true;
          alejandra.enable = true;
          deadnix.enable = true;
          statix.enable = true;
        };
      };
  in
    inputs.flakelight ./. {
      inherit inputs;
      systems = [\"x86_64-linux\" \"aarch64-linux\" \"aarch64-darwin\"];
      pname = name;

      # flakelight turns this into packages.default, a check, and an overlay,
      # so `nix flake check` builds it and the CI workflow needs nothing else.
      package = {($pkg_args | str join ', ')}:
        rustPlatform.buildRustPackage {
          pname = name;
          version = cargoPackage.version or \"0.1.0\";
          src = ./.;
          cargoLock = {
            lockFile = ($at)/Cargo.lock;
            allowBuiltinFetchGit = true;
          };($native_line)($build_line)($check_line)($in_subdir)

          meta = {
            description = \"($description)\";
            mainProgram = name;
          };
        };

      devShell = {
        packages = pkgs:
          \(with pkgs; [cargo rustc rust-analyzer clippy rustfmt]\)($extra_shell)
          ++ \(hooksFor pkgs\).enabledPackages;
        shellHook = pkgs: \(hooksFor pkgs\).shellHook;
      };

      formatter = pkgs: pkgs.alejandra;
    };
}
"
}

const CI_TEXT = "# CI for the published repo. Generated by tangled/publish/gen-standalone.nu.
#
# Inert inside the monorepo: Tangled reads .tangled/workflows from a repo's
# root, and here this sits under rust/<name>/. It becomes the published
# repo's CI once the directory is filtered out on its own.
clone:
  depth: 1
  skip: false
  submodules: false
dependencies:
  - git
  - nix
engine: microvm
image: nixos
steps:
  - command: |-
      nix --extra-experimental-features \"nix-command flakes\" \\
        flake check --print-build-logs
    name: nix flake check
when:
  - branch: '**'
    event:
      - push
"

# A pointer back to the monorepo, for a reader who arrives at a published
# repo and would otherwise open a pull request that the next sync destroys.
#
# josh ships README.md verbatim, so the published README is this one. The
# wording therefore has to be true read from either side, which is why it
# says where development happens rather than "you are looking at a mirror".
const BANNER_BEGIN = "<!-- publish:begin (generated by tangled/publish/gen-standalone.nu) -->"
const BANNER_END = "<!-- publish:end -->"

def banner-text [name: string, path: string, github: string]: nothing -> string {
    let mono = "https://tangled.org/overby.me/overby.me"
    $"($BANNER_BEGIN)
> Part of the [overby.me monorepo]\(($mono)), where this lives in
> [`($path)`]\(($mono)/tree/main/($path)) and where all development happens.
>
> It is also published on its own, as
> [tangled.org/overby.me/($name)]\(https://tangled.org/overby.me/($name)) and
> [github.com/($github)/($name)]\(https://github.com/($github)/($name)). Both
> are read-only mirrors, rebuilt from the monorepo with
> [josh]\(https://github.com/josh-project/josh): a commit made to either is
> overwritten by the next sync, so please open issues and pull requests on the
> monorepo.
($BANNER_END)"
}

# Insert or refresh the banner, after the title so the README still opens with
# its own heading.
def with-banner [readme: string, banner: string]: nothing -> string {
    let stripped = if ($readme | str contains $BANNER_BEGIN) {
        let head = ($readme | split row $BANNER_BEGIN | first)
        let tail = ($readme | split row $BANNER_END | skip 1 | str join $BANNER_END)
        $"($head)($tail | str trim -l -c "\n")"
    } else { $readme }

    let lines = ($stripped | lines)
    let title_at = ($lines | enumerate | where {|l| $l.item | str starts-with "# " } | get -o 0.index)
    if $title_at == null {
        $"($banner)\n\n($stripped)"
    } else {
        let before = ($lines | first ($title_at + 1) | str join "\n")
        let after = ($lines | skip ($title_at + 1) | str join "\n" | str trim -l -c "\n")
        $"($before)\n\n($banner)\n\n($after)"
    }
}

def main [--check, --github: string = "overby-me"]: nothing -> nothing {
    let here = ($env.FILE_PWD | default ".")
    let root = ($here | path dirname | path dirname)
    let projects = (open ($here | path join "projects.nuon"))

    # One source of truth for nixpkgs: whatever the monorepo already resolved.
    # Sharing the lock file itself would mean mapping it into every published
    # repo, and one `nix flake update` would then become N commits across N
    # repos forever. Pinning the revision gets the same synchronisation with
    # no shared surface.
    # --raw | from json: nushell does not treat .lock as JSON on its own.
    let nixpkgs_rev = (
        open --raw ($root | path join "flake.lock") | from json | get nodes.nixpkgs.locked.rev
    )
    print $"pinning nixpkgs ($nixpkgs_rev | str substring 0..9) for ($projects | length) projects"


    mut missing = []
    for p in $projects {
        let dir = ($root | path join $p.path)
        let flake = ($dir | path join "flake.nix")
        let ci = ($dir | path join ".tangled" "workflows" "ci.yml")

        # The description is the one thing worth taking from the monorepo's
        # own module, so the two do not drift apart.
        let default_nix = ($dir | path join "default.nix")
        let description = if ($default_nix | path exists) {
            let hits = (open $default_nix | lines | where {|l| $l =~ 'description = "' })
            if ($hits | is-empty) { $"A Rust rewrite, published from a monorepo" } else {
                # Unescape what default.nix escaped, then re-escape for the
                # generated string: one description contains quotes.
                $hits | first
                | str replace -r '.*description = "' ''
                | str replace -r '";.*' ''
                | str replace -a '\"' '"'
                | str replace -a '"' '\"'
            }
        } else { "A Rust rewrite, published from a monorepo" }

        # A project with sibling path dependencies publishes as several
        # directories, so its crate lands one level down under its own name.
        let subdir = if (($p | get -o deps | default []) | is-empty) { "" } else {
            $p.path | path basename
        }
        let want_flake = (
            flake-text $p.name $description $nixpkgs_rev $subdir
                ($p | get -o nativeBuildInputs | default [])
                ($p | get -o buildInputs | default [])
                ($p | get -o doCheck | default true)
        )
        if $check {
            if not ($flake | path exists) { $missing = ($missing | append $p.name) }
            continue
        }
        $want_flake | save -f $flake
        # flakelight gives every repo a checks.formatting that runs alejandra
        # over the tree, so a flake this generator wrote by hand would fail the
        # CI of the repo it was written for.
        ^alejandra --quiet $flake | ignore
        mkdir ($dir | path join ".tangled" "workflows")
        $CI_TEXT | save -f $ci

        let readme = ($dir | path join "README.md")
        let banner = if ($readme | path exists) {
            let now = (open --raw $readme)
            let want = (with-banner $now (banner-text $p.name $p.path $github))
            if $want != $now { $want | save -f $readme; " + README banner" } else { "" }
        } else { "" }
        print $"  ($p.name): flake.nix + .tangled/workflows/ci.yml($banner)"
    }

    if $check and not ($missing | is-empty) {
        error make {msg: $"missing standalone flake for: ($missing | str join ', ')"}
    }
}
