# Formatters for `nix fmt`, mirroring the formatting hooks in
# platform/nix/config/devshell/modules/git-hooks.nix.
#
# Dispatched per file: each key is a shell `case` pattern matched against the
# file's basename, and the command is invoked with the path as its final
# argument. Keys here override the framework's defaults, which use mkDefault.
#
# The configs devshell installs into the repo root (biome.jsonc, rumdl.toml) are
# gitignored, so they are absent from the source `nix flake check` copies into
# the sandbox. Point at the store copies instead.
pkgs: let
  inherit (pkgs) alejandra biome coreutils gnused rustfmt tombi;
  inherit (pkgs.pkgsUnstable) nickel;

  # No YAML formatter, and the builtin prettier must not become one:
  # .tangled/workflows/*.yml is regenerated by `nickel export | yq` on every
  # devshell entry, and prettier rewrites yq's `'**'` to `"**"`. The two would
  # overwrite each other forever, leaving checks.formatting permanently red.
  noop = "${coreutils}/bin/true";

  # A bare `rustfmt` falls back to edition 2015 and mangles newer code, so walk
  # up to the nearest Cargo.toml naming an edition. A member with
  # `edition.workspace = true` has no literal one, so the walk continues to the
  # workspace root.
  #
  # Every binary is referenced absolutely: the formatter runs with an empty
  # PATH whenever all its commands carry store context.
  rustfmtEdition = pkgs.writeShellScript "rustfmt-edition" ''
    set -eu
    file="$1"

    # The LLVM corpus is rustc's input, not our source: each .rs has a
    # checked-in .ll beside it whose DILocation records name source lines.
    # Reformatting moves those lines and desynchronises the pair, surfacing
    # later as a confusing conformance failure.
    case "$file" in
      */llvm/corpus/*) exit 0 ;;
    esac

    dir="$(${coreutils}/bin/dirname "$file")"
    edition=2024
    while :; do
      if [ -f "$dir/Cargo.toml" ]; then
        found="$(${gnused}/bin/sed -n 's/^[[:space:]]*edition[[:space:]]*=[[:space:]]*"\([0-9]\{4\}\)".*/\1/p' "$dir/Cargo.toml" | ${coreutils}/bin/head -n1)"
        if [ -n "$found" ]; then
          edition="$found"
          break
        fi
      fi
      parent="$(${coreutils}/bin/dirname "$dir")"
      if [ "$parent" = "$dir" ]; then
        break
      fi
      dir="$parent"
    done
    exec ${rustfmt}/bin/rustfmt --edition "$edition" --quiet "$file"
  '';

  biomeFormat =
    "${biome}/bin/biome format --write"
    + " --config-path=${./devshell/modules/configs/biome-nix.jsonc}";
in {
  "*.nix" = "${alejandra}/bin/alejandra --quiet";
  # rumdl has no cache.nixos.org build, so it compiles from source and
  # overflows CI's microVM disk. The no-op also keeps the builtin prettier off
  # *.md. Markdown is still formatted by the rumdl git-hook on commit.
  "*.md" = noop;
  "*.toml" = "${tombi}/bin/tombi format --offline";
  "*.ncl" = "${nickel}/bin/nickel format";
  "*.rs" = "${rustfmtEdition}";

  # Matches the devshell biome hook's types_or. CSS is absent deliberately:
  # biome can format it and the config lists it, but the hook never passes it,
  # so `nix fmt` would restyle CSS the devshell leaves alone.
  "*.js" = biomeFormat;
  "*.jsx" = biomeFormat;
  "*.ts" = biomeFormat;
  "*.tsx" = biomeFormat;
  "*.json" = biomeFormat;

  "*.yaml" = noop;
  "*.yml" = noop;

  # *.mojo is absent deliberately: `mojo format` needs the ~900 MiB Modular
  # toolchain, uncached, which on its own makes checks.formatting unbuildable
  # in CI's microVM. Mojo is formatted by the mojo-format git-hook on commit.
}
