{
  imports = [
    ./audio.nix
    ./boot.nix
    ./secrets.nix
    ./console.nix
    ./environment.nix
    ./fonts.nix
    ./hardware.nix
    ./locale.nix
    ./networking.nix
    ./nix.nix
    ./oomd.nix
    ./system.nix
    ./uinput.nix
    ./users.nix
    ./virtualisation.nix
    ./zram.nix
    ./zswap.nix
  ];
}
