#!/usr/bin/env nu

# Generate a flake and CI workflow for every published project.
#
# A published repo is a filtered copy of one directory, so it cannot use the
# monorepo's default.nix: that is a flakelight module the root flake imports,
# and it reaches for ../../../platform/nix/lib. Without something of its own, a clone is
# cargo-only and has no CI.
#
# One template covers every project because the flake reads Cargo.toml itself
# with builtins.fromTOML, so nothing needs to be restated per project. Both
# files are inert inside the monorepo: nothing imports the flake, and Tangled
# reads workflows from a repo root rather than from rust/<name>/.
#
#   nu gen-project.nu            # write them
#   nu gen-project.nu --check    # fail if any is missing or stale

# subdir is "" for the usual one-directory project, whose crate sits at the
# repo root. A project with a sibling path dependency is published as several
# directories instead, so that `path = "../pcre2"` still resolves, and then
# the crate to build is one level down.
# Everything shared between published repos lives in the nix-project
# flakelight module, so this writes only what differs: the description, the
# name, and whichever build settings the project declares in projects.nuon.
def flake-text [
    name: string
    description: string
    subdir: string = ""
    native: list<string> = []
    build: list<string> = []
    check: bool = true
    toolchain: bool = false
    build_env: record = {}
    test_flags: list<string> = []
]: nothing -> string {
    let quoted = {|xs| $xs | each {|x| $"\"($x)\"" } | str join " " }

    mut opts = []
    if not ($subdir | is-empty) { $opts = ($opts | append $"      subdir = \"($subdir)\";") }
    if not ($native | is-empty) {
        $opts = ($opts | append $"      nativeBuildInputs = [(do $quoted $native)];")
    }
    if not ($build | is-empty) {
        $opts = ($opts | append $"      buildInputs = [(do $quoted $build)];")
    }
    if not $check { $opts = ($opts | append "      doCheck = false;") }
    if not ($test_flags | is-empty) {
        $opts = ($opts | append $"      cargoTestFlags = [(do $quoted $test_flags)];")
    }
    if $toolchain { $opts = ($opts | append "      toolchain = true;") }
    if not ($build_env | is-empty) {
        let pairs = ($build_env | items {|k, v| $"        ($k) = \"($v)\";" } | str join "\n")
        $opts = ($opts | append $"      env = pkgs: {\n($pairs)\n      };")
    }

    # A pinned toolchain needs the overlay that provides rust-bin, and only
    # the project that asks for one pays for the extra input: an overlay is
    # its own flake, so carrying it in nix-project would make every published
    # repo fetch it.
    if $toolchain {
        $opts = ($opts | append "      withOverlays = [inputs.rust-overlay.overlays.default];")
    }
    let extra = if ($opts | is-empty) { "" } else { "\n" + ($opts | str join "\n") }

    let overlay_input = if not $toolchain { "" } else {
        "\n\n    # This project pins rustc through its own rust-toolchain.toml.\n    rust-overlay.url = \"github:oxalica/rust-overlay\";"
    }

    $"# Standalone build for the published repo. Generated by
# platform/tangled/publish/gen-project.nu; edit that template, not this file.
#
# The build, the devshell and its hooks, the formatter and the nixpkgs this
# resolves against are shared with every other repo published from the
# monorepo, and live in the nix-project flake. It is callable, so what is
# particular to this project is all that is left to say.
{
  description = \"($description)\";

  inputs.project.url = \"github:overby-me/nix-project\";($overlay_input)

  outputs = inputs:
    inputs.project ./. {
      name = \"($name)\";
      description = \"($description)\";($extra)
    };
}
"
}

const CI_TEXT = "# CI for the published repo. Generated by platform/tangled/publish/gen-project.nu.
#
# Inert inside the monorepo: Tangled reads .tangled/workflows from a repo's
# root, and here this sits under rust/<name>/. It becomes the published
# repo's CI once the directory is filtered out on its own.
clone:
  depth: 1
  skip: false
  submodules: false
dependencies:
  - git
  - nix
engine: microvm
image: nixos
steps:
  - command: |-
      nix --extra-experimental-features \"nix-command flakes\" \\
        flake check --print-build-logs
    name: nix flake check
when:
  - branch: '**'
    event:
      - push
"

# A pointer back to the monorepo, for a reader who arrives at a published
# repo and would otherwise open a pull request that the next sync destroys.
#
# josh ships README.md verbatim, so the published README is this one. The
# wording therefore has to be true read from either side, which is why it
# says where development happens rather than "you are looking at a mirror".
# Deliberately free of the script name: the marker is how an existing
# banner is found, so embedding a filename means renaming the script
# silently appends a second banner to every README.
const BANNER_BEGIN = "<!-- publish:begin -->"
const BANNER_END = "<!-- publish:end -->"

def banner-text [name: string, path: string, github: string]: nothing -> string {
    let mono = "https://tangled.org/overby.me/overby.me"
    $"($BANNER_BEGIN)
> Part of the [overby.me monorepo]\(($mono)), where this lives in
> [`($path)`]\(($mono)/tree/main/($path)) and where all development happens.
>
> It is also published on its own, as
> [tangled.org/overby.me/($name)]\(https://tangled.org/overby.me/($name)) and
> [github.com/($github)/($name)]\(https://github.com/($github)/($name)). Both
> are read-only mirrors, rebuilt from the monorepo with
> [josh]\(https://github.com/josh-project/josh): a commit made to either is
> overwritten by the next sync, so please open issues and pull requests on the
> monorepo.
($BANNER_END)"
}

# Insert or refresh the banner, after the title so the README still opens with
# its own heading.
def with-banner [readme: string, banner: string]: nothing -> string {
    let stripped = if ($readme | str contains $BANNER_BEGIN) {
        let head = ($readme | split row $BANNER_BEGIN | first)
        let tail = ($readme | split row $BANNER_END | skip 1 | str join $BANNER_END)
        $"($head)($tail | str trim -l -c "\n")"
    } else { $readme }

    let lines = ($stripped | lines)
    let title_at = ($lines | enumerate | where {|l| $l.item | str starts-with "# " } | get -o 0.index)
    if $title_at == null {
        $"($banner)\n\n($stripped)"
    } else {
        let before = ($lines | first ($title_at + 1) | str join "\n")
        let after = ($lines | skip ($title_at + 1) | str join "\n" | str trim -l -c "\n")
        $"($before)\n\n($banner)\n\n($after)"
    }
}

def main [--check, --github: string = "overby-me"]: nothing -> nothing {
    let here = ($env.FILE_PWD | default ".")
    # Walk up to the monorepo root rather than counting directories, which
    # went wrong the moment this script moved an area deeper.
    let root = (
        1..6 | reduce --fold $here {|_, acc|
            if ($acc | path join "flake.lock" | path exists) { $acc } else { $acc | path dirname }
        }
    )
    let projects = (open ($here | path join "projects.nuon"))

    print $"writing flakes for ($projects | length) projects"

    mut missing = []
    for p in $projects {
        let dir = ($root | path join $p.path)
        let flake = ($dir | path join "flake.nix")
        let ci = ($dir | path join ".tangled" "workflows" "ci.yml")

        # The description is the one thing worth taking from the monorepo's
        # own module, so the two do not drift apart.
        # A repo's description is a fact about the project, and for a
        # workspace no single package's meta states it: fe-c's first entry
        # describes its runtime crate. State it in projects.nuon where it
        # differs, and scrape default.nix otherwise.
        let stated = ($p | get -o description)
        let default_nix = ($dir | path join "default.nix")
        let description = if ($default_nix | path exists) {
            let hits = (open $default_nix | lines | where {|l| $l =~ 'description = "' })
            if ($hits | is-empty) { $"A Rust rewrite, published from a monorepo" } else {
                # Unescape what default.nix escaped, then re-escape for the
                # generated string: one description contains quotes.
                $hits | first
                | str replace -r '.*description = "' ''
                | str replace -r '";.*' ''
                | str replace -a '\"' '"'
                | str replace -a '"' '\"'
            }
        } else { "A Rust rewrite, published from a monorepo" }
        let description = ($stated | default $description)

        # A project with sibling path dependencies publishes as several
        # directories, so its crate lands one level down under its own name.
        let subdir = if (($p | get -o deps | default []) | is-empty) { "" } else {
            $p.path | path basename
        }
        # The generated flake builds a Rust crate, so a project without a
        # Cargo.toml gets none. nix-project is the module the others
        # import, and writes its own.
        let is_crate = ($dir | path join "Cargo.toml" | path exists)

        let want_flake = if not $is_crate { "" } else { (
            flake-text $p.name $description $subdir
                ($p | get -o nativeBuildInputs | default [])
                ($p | get -o buildInputs | default [])
                ($p | get -o doCheck | default true)
                ($p | get -o toolchain | default false)
                ($p | get -o env | default {})
                ($p | get -o cargoTestFlags | default [])
        ) }
        if $check {
            if not ($flake | path exists) { $missing = ($missing | append $p.name) }
            continue
        }
        if $is_crate {
            $want_flake | save -f $flake
            # flakelight gives every repo a checks.formatting that runs
            # alejandra over the tree, so a flake this generator wrote by hand
            # would fail the CI of the repo it was written for.
            ^alejandra --quiet $flake | ignore
        }
        mkdir ($dir | path join ".tangled" "workflows")
        $CI_TEXT | save -f $ci

        # A published repo's README should be titled after the project, not
        # after the directory it used to live in: nineteen still said
        # rust-awk after the rename, which is the first line a visitor reads.
        # The heading is prose (Oxidized Systemd), the repo name is the
        # identifier (oxidized-systemd); both are derived from the same name
        # so they cannot disagree.
        let readme = ($dir | path join "README.md")
        if ($readme | path exists) {
            let words = ($p.name | split row "-")
            let special = {
                cli: "CLI", llvm: "LLVM", gcc: "GCC", pcre2: "PCRE2",
                nixos: "NixOS", pipewire: "PipeWire", xz: "XZ", wasm: "WASM"
            }
            let want = if ($p.name in ["fe-c" "h26xtoav1"]) {
                if $p.name == "fe-c" { "Fe-C" } else { "h26xtoav1" }
            } else if ($p.name | str ends-with "pkg-config") {
                "Oxidized pkg-config"
            } else {
                $words | each {|w| ($special | get -o $w | default ($w | str capitalize)) } | str join " "
            }
            let txt = (open --raw $readme)
            let h1 = ($txt | lines | where {|l| $l | str starts-with "# " } | get -o 0)
            if $h1 != null and $h1 != $"# ($want)" {
                $txt | str replace $h1 $"# ($want)" | save -f $readme
                print $"  ($p.name): retitled to ($want)"
            }
        }
        let banner = if ($readme | path exists) {
            let now = (open --raw $readme)
            let want = (with-banner $now (banner-text $p.name $p.path $github))
            if $want != $now { $want | save -f $readme; " + README banner" } else { "" }
        } else { "" }
        let what = if $is_crate { "flake.nix + " } else { "" }
        print $"  ($p.name): ($what).tangled/workflows/ci.yml($banner)"
    }

    if $check and not ($missing | is-empty) {
        error make {msg: $"missing flake for: ($missing | str join ', ')"}
    }
}
