#!/usr/bin/env nu

# Generate a standalone flake and CI workflow for every published project.
#
# A published repo is a filtered copy of one directory, so it cannot use the
# monorepo's default.nix: that is a flakelight module the root flake imports,
# and it reaches for ../../../platform/nix/lib. Without something of its own, a clone is
# cargo-only and has no CI.
#
# One template covers every project because the flake reads Cargo.toml itself
# with builtins.fromTOML, so nothing needs to be restated per project. Both
# files are inert inside the monorepo: nothing imports the flake, and Tangled
# reads workflows from a repo root rather than from rust/<name>/.
#
#   nu gen-standalone.nu            # write them
#   nu gen-standalone.nu --check    # fail if any is missing or stale

# subdir is "" for the usual one-directory project, whose crate sits at the
# repo root. A project with a sibling path dependency is published as several
# directories instead, so that `path = "../pcre2"` still resolves, and then
# the crate to build is one level down.
# Everything shared between published repos lives in the standalone
# flakelight module, so this writes only what differs: the description, the
# name, and whichever build settings the project declares in projects.nuon.
def flake-text [
    name: string
    description: string
    nixpkgs_rev: string
    subdir: string = ""
    native: list<string> = []
    build: list<string> = []
    check: bool = true
    toolchain: bool = false
    build_env: record = {}
    test_flags: list<string> = []
]: nothing -> string {
    let quoted = {|xs| $xs | each {|x| $"\"($x)\"" } | str join " " }

    mut opts = []
    if not ($subdir | is-empty) { $opts = ($opts | append $"        subdir = \"($subdir)\";") }
    if not ($native | is-empty) {
        $opts = ($opts | append $"        nativeBuildInputs = [(do $quoted $native)];")
    }
    if not ($build | is-empty) {
        $opts = ($opts | append $"        buildInputs = [(do $quoted $build)];")
    }
    if not $check { $opts = ($opts | append "        doCheck = false;") }
    if not ($test_flags | is-empty) {
        $opts = ($opts | append $"        cargoTestFlags = [(do $quoted $test_flags)];")
    }
    if $toolchain { $opts = ($opts | append "        toolchain = true;") }
    if not ($build_env | is-empty) {
        let pairs = ($build_env | items {|k, v| $"          ($k) = \"($v)\";" } | str join "\n")
        $opts = ($opts | append $"        env = pkgs: {\n($pairs)\n        };")
    }
    let extra = if ($opts | is-empty) { "" } else { "\n" + ($opts | str join "\n") }

    # A pinned toolchain needs the overlay that provides rust-bin, and only
    # the project that asks for one pays for the extra input.
    let overlay_input = if not $toolchain { "" } else {
        "\n\n    # This project pins rustc through its own rust-toolchain.toml.\n    rust-overlay = {\n      url = \"github:oxalica/rust-overlay\";\n      inputs.nixpkgs.follows = \"nixpkgs\";\n    };"
    }
    let overlay_line = if not $toolchain { "" } else {
        "\n      withOverlays = [inputs.rust-overlay.overlays.default];\n"
    }

    $"# Standalone build for the published repo. Generated by
# platform/tangled/publish/gen-standalone.nu; edit that template, not this file.
#
# The build, the devshell and its hooks, and the formatter are shared with
# every other repo published from the monorepo, and live in the standalone
# module. Only what is particular to this project is stated here.
{
  description = \"($description)\";

  inputs = {
    # Pinned to the same revision the monorepo resolves, so every published
    # repo builds against identical nixpkgs and they cannot drift apart.
    # Change it by re-running the generator, never here.
    nixpkgs.url = \"github:NixOS/nixpkgs/($nixpkgs_rev)\";

    flakelight = {
      url = \"github:accelbread/flakelight\";
      inputs.nixpkgs.follows = \"nixpkgs\";
    };

    standalone = {
      url = \"github:overby-me/nix-standalone\";
      inputs.nixpkgs.follows = \"nixpkgs\";
      inputs.flakelight.follows = \"flakelight\";
    };($overlay_input)
  };

  outputs = inputs:
    inputs.flakelight ./. {
      inherit inputs;
      imports = [inputs.standalone.flakelightModules.default];
($overlay_line)
      description = \"($description)\";

      standalone = {
        name = \"($name)\";
        root = ./.;($extra)
      };
    };
}
"
}

const CI_TEXT = "# CI for the published repo. Generated by platform/tangled/publish/gen-standalone.nu.
#
# Inert inside the monorepo: Tangled reads .tangled/workflows from a repo's
# root, and here this sits under rust/<name>/. It becomes the published
# repo's CI once the directory is filtered out on its own.
clone:
  depth: 1
  skip: false
  submodules: false
dependencies:
  - git
  - nix
engine: microvm
image: nixos
steps:
  - command: |-
      nix --extra-experimental-features \"nix-command flakes\" \\
        flake check --print-build-logs
    name: nix flake check
when:
  - branch: '**'
    event:
      - push
"

# A pointer back to the monorepo, for a reader who arrives at a published
# repo and would otherwise open a pull request that the next sync destroys.
#
# josh ships README.md verbatim, so the published README is this one. The
# wording therefore has to be true read from either side, which is why it
# says where development happens rather than "you are looking at a mirror".
const BANNER_BEGIN = "<!-- publish:begin (generated by platform/tangled/publish/gen-standalone.nu) -->"
const BANNER_END = "<!-- publish:end -->"

def banner-text [name: string, path: string, github: string]: nothing -> string {
    let mono = "https://tangled.org/overby.me/overby.me"
    $"($BANNER_BEGIN)
> Part of the [overby.me monorepo]\(($mono)), where this lives in
> [`($path)`]\(($mono)/tree/main/($path)) and where all development happens.
>
> It is also published on its own, as
> [tangled.org/overby.me/($name)]\(https://tangled.org/overby.me/($name)) and
> [github.com/($github)/($name)]\(https://github.com/($github)/($name)). Both
> are read-only mirrors, rebuilt from the monorepo with
> [josh]\(https://github.com/josh-project/josh): a commit made to either is
> overwritten by the next sync, so please open issues and pull requests on the
> monorepo.
($BANNER_END)"
}

# Insert or refresh the banner, after the title so the README still opens with
# its own heading.
def with-banner [readme: string, banner: string]: nothing -> string {
    let stripped = if ($readme | str contains $BANNER_BEGIN) {
        let head = ($readme | split row $BANNER_BEGIN | first)
        let tail = ($readme | split row $BANNER_END | skip 1 | str join $BANNER_END)
        $"($head)($tail | str trim -l -c "\n")"
    } else { $readme }

    let lines = ($stripped | lines)
    let title_at = ($lines | enumerate | where {|l| $l.item | str starts-with "# " } | get -o 0.index)
    if $title_at == null {
        $"($banner)\n\n($stripped)"
    } else {
        let before = ($lines | first ($title_at + 1) | str join "\n")
        let after = ($lines | skip ($title_at + 1) | str join "\n" | str trim -l -c "\n")
        $"($before)\n\n($banner)\n\n($after)"
    }
}

def main [--check, --github: string = "overby-me"]: nothing -> nothing {
    let here = ($env.FILE_PWD | default ".")
    # Walk up to the monorepo root rather than counting directories, which
    # went wrong the moment this script moved an area deeper.
    let root = (
        1..6 | reduce --fold $here {|_, acc|
            if ($acc | path join "flake.lock" | path exists) { $acc } else { $acc | path dirname }
        }
    )
    let projects = (open ($here | path join "projects.nuon"))

    # One source of truth for nixpkgs: whatever the monorepo already resolved.
    # Sharing the lock file itself would mean mapping it into every published
    # repo, and one `nix flake update` would then become N commits across N
    # repos forever. Pinning the revision gets the same synchronisation with
    # no shared surface.
    # --raw | from json: nushell does not treat .lock as JSON on its own.
    let nixpkgs_rev = (
        open --raw ($root | path join "flake.lock") | from json | get nodes.nixpkgs.locked.rev
    )
    print $"pinning nixpkgs ($nixpkgs_rev | str substring 0..9) for ($projects | length) projects"


    mut missing = []
    for p in $projects {
        let dir = ($root | path join $p.path)
        let flake = ($dir | path join "flake.nix")
        let ci = ($dir | path join ".tangled" "workflows" "ci.yml")

        # The description is the one thing worth taking from the monorepo's
        # own module, so the two do not drift apart.
        let default_nix = ($dir | path join "default.nix")
        let description = if ($default_nix | path exists) {
            let hits = (open $default_nix | lines | where {|l| $l =~ 'description = "' })
            if ($hits | is-empty) { $"A Rust rewrite, published from a monorepo" } else {
                # Unescape what default.nix escaped, then re-escape for the
                # generated string: one description contains quotes.
                $hits | first
                | str replace -r '.*description = "' ''
                | str replace -r '";.*' ''
                | str replace -a '\"' '"'
                | str replace -a '"' '\"'
            }
        } else { "A Rust rewrite, published from a monorepo" }

        # A project with sibling path dependencies publishes as several
        # directories, so its crate lands one level down under its own name.
        let subdir = if (($p | get -o deps | default []) | is-empty) { "" } else {
            $p.path | path basename
        }
        # The generated flake builds a Rust crate, so a project without a
        # Cargo.toml gets none. nix-standalone is the module the others
        # import, and writes its own.
        let is_crate = ($dir | path join "Cargo.toml" | path exists)

        let want_flake = if not $is_crate { "" } else { (
            flake-text $p.name $description $nixpkgs_rev $subdir
                ($p | get -o nativeBuildInputs | default [])
                ($p | get -o buildInputs | default [])
                ($p | get -o doCheck | default true)
                ($p | get -o toolchain | default false)
                ($p | get -o env | default {})
                ($p | get -o cargoTestFlags | default [])
        ) }
        if $check {
            if not ($flake | path exists) { $missing = ($missing | append $p.name) }
            continue
        }
        if $is_crate {
            $want_flake | save -f $flake
            # flakelight gives every repo a checks.formatting that runs
            # alejandra over the tree, so a flake this generator wrote by hand
            # would fail the CI of the repo it was written for.
            ^alejandra --quiet $flake | ignore
        }
        mkdir ($dir | path join ".tangled" "workflows")
        $CI_TEXT | save -f $ci

        let readme = ($dir | path join "README.md")
        let banner = if ($readme | path exists) {
            let now = (open --raw $readme)
            let want = (with-banner $now (banner-text $p.name $p.path $github))
            if $want != $now { $want | save -f $readme; " + README banner" } else { "" }
        } else { "" }
        let what = if $is_crate { "flake.nix + " } else { "" }
        print $"  ($p.name): ($what).tangled/workflows/ci.yml($banner)"
    }

    if $check and not ($missing | is-empty) {
        error make {msg: $"missing standalone flake for: ($missing | str join ', ')"}
    }
}
